// ═══════════════════════════════════════════════════════════════════
// READING-DATA.JS — Bilingual structured notes for topics (StudyLab)
// ═══════════════════════════════════════════════════════════════════
// RD — READING DATA: Bilingual structured notes, keyed by
// RD[SubjectName][ExactTopicNameFromSD.topics] = { hi: [...], en: [...] }
//
// Block types:
//   { type: "heading", text: "..." }   → bold colored heading
//   { type: "bullet",  text: "..." }   → bullet point line
//   { type: "text",    text: "..." }   → plain paragraph
//
// Highlight any key term/date/name by wrapping it in <hl>...</hl>
// — it renders in the subject's accent color with a soft background.
//
// IMPORTANT: the topic key here must match EXACTLY (same spelling/
// casing) as the string used in SD[Subject].topics below, otherwise
// the "Read" card won't find it and will show "Coming soon".
// ═══════════════════════════════════════════════════════════════════
window.RD = {
    "History": {
        "Jainism": {
            hi: [
                { type: "heading", text: "6. जैन धर्म" },
                { type: "bullet", text: "जैनधर्म के संस्थापक एवं प्रथम तीर्थंकर <hl>ऋषभदेव</hl> थे।" },
                { type: "bullet", text: "<hl>कल्पसूत्र</hl> जैन परम्परा का सर्वाधिक लोकप्रिय ग्रंथ है। इसके एक भाग में जैन धर्म के <hl>24 तीर्थंकरों</hl> के जन्म से लेकर निर्वाण तक की विविध घटनाओं का वर्णन किया गया है। उनके जीवन की पाँच प्रमुख घटनाओं को विशेष रूप से प्रस्तुत किया गया है—<hl>गर्भाधान, जन्म, गृहत्याग, ज्ञान प्राप्ति व प्रथम उपदेश</hl>।" },
                { type: "bullet", text: "जैनधर्म के <hl>23वें तीर्थंकर पार्श्वनाथ</hl> थे जो काशी के इक्ष्वाकु वंशीय राजा <hl>अश्वसेन</hl> के पुत्र थे। इन्होंने 30 वर्ष की अवस्था में संन्यास-जीवन को स्वीकारा। इनके द्वारा दी गयी शिक्षा थी—1. हिंसा न करना, 2. सदा सत्य बोलना, 3. चोरी न करना तथा 4. सम्पत्ति न रखना।" },
                { type: "bullet", text: "<hl>महावीर स्वामी</hl> जैन धर्म के <hl>24वें एवं अंतिम तीर्थंकर</hl> हुए।" },
                { type: "bullet", text: "महावीर का जन्म <hl>540 ईसा पूर्व</hl> में <hl>कुण्डग्राम (वैशाली)</hl> में हुआ था। इनके पिता <hl>सिद्धार्थ</hl> 'ज्ञातृक कुल' के सरदार थे और माता <hl>त्रिशला</hl> लिच्छवि राजा <hl>चेटक</hl> की बहन थी।" },
                { type: "bullet", text: "महावीर की पत्नी का नाम <hl>यशोदा</hl> एवं पुत्री का नाम <hl>अनोज्जा प्रियदर्शनी</hl> था।" },
                { type: "bullet", text: "महावीर के बचपन का नाम <hl>वर्द्धमान</hl> था। इन्होंने 30 वर्ष की उम्र में माता-पिता की मृत्यु के पश्चात् अपने बड़े भाई <hl>नंदिवर्धन</hl> से अनुमति लेकर संन्यास-जीवन को स्वीकारा था।" },
                { type: "bullet", text: "<hl>12 वर्षों</hl> की कठिन तपस्या के बाद महावीर को जृम्भिक के समीप <hl>ऋजुपालिका नदी</hl> के तट पर साल वृक्ष के नीचे तपस्या करते हुए सम्पूर्ण ज्ञान (कैवल्य ज्ञान) का बोध हुआ। इसी समय से महावीर <hl>जिन (विजेता), अर्हत (पूज्य)</hl> और <hl>निर्ग्रन्थ (बंधनहीन)</hl> कहलाए।" },
                { type: "heading", text: "महावीर के गर्भाधान का स्वप्न" },
                { type: "bullet", text: "महावीर के गर्भाधान के समय उनकी माता <hl>त्रिशला</hl> ने <hl>14 वस्तुओं</hl> का स्वप्न देखा।" },
                { type: "bullet", text: "14 वस्तुएँ थीं—<hl>हाथी, बैल, शेर, देवी लक्ष्मी, कलश, पालकी, सरोवर, छोटी नदी, अग्नि, ध्वज, माला, रत्नों का ढेर, सूर्य एवं चन्द्रमा</hl>।" },
                { type: "bullet", text: "उन्होंने अपने सपने के बारे में ज्योतिषियों से बात की। ज्योतिषी ने बताया कि वे एक ऐसे पुत्र को जन्म देंगी जो या तो राजाध्यक्ष होगा अथवा एक महान संत।" },
                { type: "heading", text: "महावीर की शिक्षाएँ एवं अनुयायी" },
                { type: "bullet", text: "<hl>उत्तरायण सूत्र</hl> में महावीर की शिक्षाओं का वर्णन है, जहाँ भिक्षुओं के आचार संहिता का पालन करने का वर्णन किया गया है।" },
                { type: "bullet", text: "महावीर ने अपना उपदेश <hl>प्राकृत (अर्धमागधी)</hl> भाषा में दिया।" },
                { type: "bullet", text: "महावीर के अनुयायियों को मूलतः <hl>निर्ग्रंथ</hl> कहा जाता था।" },
                { type: "bullet", text: "महावीर के प्रथम अनुयायी उनके दामाद <hl>जामिल</hl> बने।" },
                { type: "bullet", text: "प्रथम जैन भिक्षुणी नरेश दधिवाहन की पुत्री <hl>चम्पा</hl> थी।" },
                { type: "heading", text: "प्रमुख जैन तीर्थंकर और उनके प्रतीक चिह्न" },
                { type: "bullet", text: "<hl>ऋषभदेव (प्रथम)</hl> — प्रतीक चिह्न: साँड (बैल)" },
                { type: "bullet", text: "<hl>अजितनाथ (द्वितीय)</hl> — प्रतीक चिह्न: हाथी" },
                { type: "bullet", text: "<hl>संभव (तृतीय)</hl> — प्रतीक चिह्न: घोड़ा" },
                { type: "bullet", text: "<hl>संपार्श्व (सप्तम)</hl> — प्रतीक चिह्न: स्वास्तिक" },
                { type: "bullet", text: "<hl>शांति (सोलहवाँ)</hl> — प्रतीक चिह्न: हिरण" },
                { type: "bullet", text: "<hl>अरनाथ (अठारहवाँ)</hl> — प्रतीक चिह्न: मीन (मछली)" },
                { type: "bullet", text: "<hl>नामि (इक्कीसवें)</hl> — प्रतीक चिह्न: नीलकमल" },
                { type: "bullet", text: "<hl>अरिष्टनेमि (बाइसवें)</hl> — प्रतीक चिह्न: शंख" },
                { type: "bullet", text: "<hl>पार्श्व (तेइसवें)</hl> — प्रतीक चिह्न: सर्प" },
                { type: "bullet", text: "<hl>महावीर (चौबीसवें)</hl> — प्रतीक चिह्न: सिंह" },
                { type: "bullet", text: "नोट: दो जैन तीर्थंकरों <hl>ऋषभदेव</hl> एवं <hl>अरिष्टनेमि</hl> के नामों का उल्लेख ऋग्वेद में मिलता है। अरिष्टनेमि को भगवान कृष्ण का निकट संबंधी माना जाता है।" },
                { type: "bullet", text: "महावीर ने अपने शिष्यों को <hl>11 गणधरों</hl> में विभाजित किया।" },
                { type: "bullet", text: "<hl>आर्य सुधर्मा</hl> अकेला ऐसा गणधर था जो महावीर की मृत्यु के बाद भी जीवित रहा और जो जैनधर्म का प्रथम थेरा या मुख्य उपदेशक हुआ।" },
                { type: "bullet", text: "स्वामी महावीर के भिक्षुणी संघ की प्रधान <hl>चन्दना</hl> थी।" },
                { type: "heading", text: "जैन धर्म का विभाजन: श्वेताम्बर एवं दिगम्बर" },
                { type: "bullet", text: "लगभग <hl>300 ईसा पूर्व</hl> में मगध में 12 वर्षों का भीषण अकाल पड़ा, जिसके कारण <hl>भद्रबाहु</hl> अपने शिष्यों सहित कर्नाटक चले गए। किंतु कुछ अनुयायी <hl>स्थूलभद्र</hl> के साथ मगध में ही रुक गए।" },
                { type: "bullet", text: "भद्रबाहु के वापस लौटने पर मगध के साधुओं से उनका गहरा मतभेद हो गया जिसके परिणामस्वरूप जैन मत <hl>श्वेताम्बर</hl> एवं <hl>दिगम्बर</hl> नामक दो सम्प्रदायों में बँट गया।" },
                { type: "bullet", text: "स्थूलभद्र के शिष्य <hl>श्वेताम्बर (श्वेत वस्त्र धारण करने वाले)</hl> एवं भद्रबाहु के शिष्य <hl>दिगम्बर (नग्न रहने वाले)</hl> कहलाए।" },
                { type: "heading", text: "दिगम्बर एवं श्वेताम्बर सम्प्रदायों में अंतर" },
                { type: "bullet", text: "दिगम्बर: ये पाँचों निग्रहों का पालन करते हैं यथा सत्य, अहिंसा, अस्तेय, अपरिग्रह एवं ब्रह्मचर्य।" },
                { type: "bullet", text: "श्वेताम्बर: ये केवल चार निग्रहों का पालन करते हैं यथा सत्य, अहिंसा, अस्तेय एवं अपरिग्रह। ब्रह्मचर्य का पालन नहीं करते।" },
                { type: "bullet", text: "दिगम्बर: यह सम्प्रदाय 6 अनंत पदार्थों का अस्तित्व स्वीकार करता है — आत्मा (जीव), पदार्थ (पुद्गल), अंतरिक्ष (आकाश), गति (धर्म), स्थिरता (अधर्म) तथा समय (काल)।" },
                { type: "bullet", text: "श्वेताम्बर: यह समय (काल) को छोड़कर 5 अनंत पदार्थों का अस्तित्व स्वीकार करता है यथा आत्मा, पदार्थ, अंतरिक्ष, गति एवं स्थिरता।" },
                { type: "bullet", text: "दिगम्बर: इसमें महिलाएँ तीर्थंकर नहीं हो सकतीं।" },
                { type: "bullet", text: "श्वेताम्बर: इसमें महिलाएँ भी तीर्थंकर हो सकती हैं।" },
                { type: "bullet", text: "दिगम्बर: ये मानते हैं कि महावीर ने विवाह नहीं किया था।" },
                { type: "bullet", text: "श्वेताम्बर: ये मानते हैं कि महावीर ने विवाह किया था और उन्हें संतान थी।" },
                { type: "bullet", text: "दिगम्बर: ये मानते हैं कि 19वें तीर्थंकर मल्लिनाथ पुरुष थे।" },
                { type: "bullet", text: "श्वेताम्बर: ये मानते हैं कि मल्लिनाथ स्त्री थीं।" },
                { type: "bullet", text: "दिगम्बर: इनका कहना है कि मूल जैन आगम ग्रंथ खो चुका है।" },
                { type: "bullet", text: "श्वेताम्बर: ये जैन आगम ग्रंथ को स्वीकार करते हैं।" },
                { type: "bullet", text: "दिगम्बर: ये मानते हैं कि कैवल्य प्राप्ति के बाद उपवास करके रहा जा सकता है।" },
                { type: "bullet", text: "श्वेताम्बर: ये मानते हैं कि कैवल्य प्राप्ति के बाद भी भोजन की आवश्यकता पड़ती है।" },
                { type: "bullet", text: "दिगम्बर: ये स्त्रियों के इसी जीवन में मुक्ति का विरोध करते हैं।" },
                { type: "bullet", text: "श्वेताम्बर: ये इसी जीवन में स्त्रियों की मुक्ति की अधिकारिणी मानते हैं।" },
                { type: "bullet", text: "दिगम्बर: ये सफेद वस्त्र नहीं पहनते हैं, क्योंकि इसे निर्वाण (मोक्ष) में बाधक मानते हैं।" },
                { type: "bullet", text: "श्वेताम्बर: ये सफेद वस्त्र पहनते हैं तथा इसे निर्वाण (मोक्ष) में बाधक नहीं मानते हैं।" },
                { type: "heading", text: "जैन संगीतियाँ" },
                { type: "bullet", text: "प्रथम जैन संगीति <hl>300 ईसा पूर्व</hl> में <hl>पाटलिपुत्र</hl> में हुई, जिसकी अध्यक्षता <hl>स्थूलभद्र</hl> ने की।" },
                { type: "bullet", text: "द्वितीय जैन संगीति <hl>512 ई.</hl> में <hl>वल्लभी (गुजरात)</hl> में हुई, जिसकी अध्यक्षता <hl>क्षमाश्रवण</hl> ने की।" },
                { type: "heading", text: "जैन धर्म के सिद्धांत" },
                { type: "bullet", text: "जैनधर्म के त्रिरत्न हैं—1. <hl>सम्यक् दर्शन</hl> (सही विश्वास) 2. <hl>सम्यक ज्ञान</hl> (सही ज्ञान) और 3. <hl>सम्यक आचरण</hl> (सही आचरण)।" },
                { type: "bullet", text: "त्रिरत्न के अनुशीलन में निम्न <hl>पाँच महाव्रतों</hl> का पालन अनिवार्य है—<hl>अहिंसा, सत्य वचन, अस्तेय, अपरिग्रह एवं ब्रह्मचर्य</hl>।" },
                { type: "bullet", text: "जैन धर्म में <hl>चार वर्गों (शिक्षा, अन्न, चिकित्सा और आवास)</hl> के दान के सिद्धान्त ने इसे लोकप्रिय बनाने में मदद की।" },
                { type: "bullet", text: "जैनधर्म में <hl>ईश्वर की मान्यता नहीं</hl> है।" },
                { type: "bullet", text: "जैनधर्म में <hl>आत्मा की मान्यता</hl> है। जैनियों के अनुसार, जीव (आत्मा) न केवल मनुष्यों व पशु-पक्षियों में वरन पेड़-पौधे, पत्थरों व जल में भी पाया जाता है। जैनधर्म के अनुसार एक आत्मा अपने कर्म के आधार पर जन्म एवं मृत्यु के चक्र में भ्रमण करती है।" },
                { type: "heading", text: "जैन दर्शन: जीव-अजीव एवं चार गतियाँ" },
                { type: "bullet", text: "जैन दर्शन में जीवन या अस्तित्व के चार प्रमुख रूप (जिन्हें <hl>गतियाँ</hl> भी कहा जाता है) निम्नलिखित हैं:" },
                { type: "bullet", text: "1. <hl>मनुष्य गति</hl>: मानव का अस्तित्व। जैन मान्यता के अनुसार केवल इसी गति से मोक्ष (जन्म-मरण के चक्र से मुक्ति) प्राप्त किया जा सकता है।" },
                { type: "bullet", text: "2. <hl>देवगति</hl>: स्वर्गीय प्राणियों या देवताओं का अस्तित्व।" },
                { type: "bullet", text: "3. <hl>तिर्यच गति</hl>: पशु, पक्षी, पेड़-पौधे और सूक्ष्म जीवों का अस्तित्व।" },
                { type: "bullet", text: "4. <hl>नरक गति</hl>: नारकीय प्राणियों का अस्तित्व।" },
                { type: "bullet", text: "इन चारों अवस्थाओं से पार जाकर जब आत्मा अपने सभी कर्मों का नाश कर लेती है, तब उसे <hl>मोक्ष</hl> की प्राप्ति होती है।" },
                { type: "bullet", text: "जैन धर्म के अनुसार, सृष्टि का निर्माण <hl>जीव तथा अजीव</hl> नामक दो मूल तत्वों से हुआ है। जीव चेतन तत्व है और अजीव अचेतन जड़ तत्व (<hl>पुद्गल, काल, आकाश, धर्म व अधर्म</hl>) है।" },
                { type: "bullet", text: "महावीर <hl>पुनर्जन्म एवं कर्मवाद</hl> में विश्वास करते थे।" },
                { type: "bullet", text: "जैनधर्म के सप्तभंगी ज्ञान के अन्य नाम <hl>स्यादवाद</hl> व <hl>अनेकांतवाद</hl> हैं, जो जैन धर्म का मौलिक सिद्धांत है।" },
                { type: "bullet", text: "जैनधर्म ने अपने आध्यात्मिक विचारों को <hl>सांख्य दर्शन</hl> से ग्रहण किया। जैन धर्म के प्रमुख त्योहार हैं: <hl>महावीर जयंती, पर्युषण अष्टान्हिका, एवं दीपावली</hl>।" },
                { type: "heading", text: "जैन धर्म से जुड़े राजा एवं प्रमुख स्थल" },
                { type: "bullet", text: "जैनधर्म मानने वाले कुछ राजा थे—<hl>उदयिन, वंदराजा, चन्द्रगुप्त मौर्य, कलिंग नरेश खारवेल, राष्ट्रकूट राजा अमोघवर्ष, चंदेल शासक</hl>।" },
                { type: "bullet", text: "मैसूर के गंग वंश के राजाओं के सेनापति एवं प्रधानमंत्री <hl>चामुण्डाराय</hl> के प्रोत्साहन से कर्नाटक के <hl>श्रवणबेलगोला</hl> में 10वीं शताब्दी के मध्य भाग में विशाल बाहुबलि की ग्रेनाइट पत्थर की मूर्ति (<hl>गोमतेश्वर की मूर्ति</hl>) का निर्माण किया गया।" },
                { type: "bullet", text: "गोमतेश्वर की प्रतिमा <hl>कायोत्सर्ग मुद्रा</hl> में है। इसमें बाहुबलि तपस्या की इस मुद्रा में अपने चारों ओर के वातावरण से अनभिज्ञ दिखाए गए हैं। उनके पैरों में साँप लपेटे हुए तथा चींटियों ने मिट्टी के घरौंदे बना दिए हैं।" },
                { type: "bullet", text: "यह मूर्ति <hl>18 मीटर या 57 फीट</hl> ऊँची है एवं एक ही चट्टान को काटकर बनाई गई है। यह विश्व में एक ही पत्थर से बनी बिना किसी सहारे के खड़ी सबसे लंबी मूर्ति है।" },
                { type: "bullet", text: "राजस्थान में <hl>माउन्ट आबू</hl> पर स्थित जैन मंदिर <hl>विमलशाह</hl> द्वारा बनवाए गए थे।" },
                { type: "bullet", text: "<hl>काठियावाड़ (गुजरात)</hl> में पालिताना के निकट <hl>शत्रुंजय की पहाड़ियों</hl> में एक विशाल जैन तीर्थस्थल है जहाँ एक साथ जुड़े हुए बीसियों मंदिर दर्शनीय हैं।" },
                { type: "bullet", text: "<hl>खजुराहो</hl> में जैन मंदिरों का निर्माण <hl>चंदेल शासकों</hl> द्वारा किया गया।" },
                { type: "bullet", text: "आधुनिक तमिलनाडु के <hl>पुदुकोट्टई</hl> जिले में स्थित <hl>सित्तन्नवासल की गुफाएँ</hl> जैन धर्म से संबंधित हैं।" },
                { type: "bullet", text: "मौर्योत्तर युग में <hl>मथुरा</hl> जैन धर्म का प्रसिद्ध केन्द्र था। मथुरा कला का संबंध जैनधर्म से है।" },
                { type: "heading", text: "महावीर का निर्वाण एवं अन्य तथ्य" },
                { type: "bullet", text: "जैन तीर्थंकरों की जीवनी <hl>भद्रबाहु</hl> द्वारा रचित <hl>कल्पसूत्र</hl> में है।" },
                { type: "bullet", text: "<hl>72 वर्ष</hl> की आयु में महावीर की मृत्यु (निर्वाण) <hl>468 ईसा पूर्व</hl> में बिहार राज्य के <hl>पावापुरी (राजगीर)</hl> में हो गई।" },
                { type: "bullet", text: "मल्लराजा <hl>सृस्तिपाल</hl> के राजप्रासाद में महावीर स्वामी को निर्वाण प्राप्त हुआ था।" },
                { type: "bullet", text: "<hl>जीवक चिन्तामणि</hl> जैन संत <hl>तिरुत्तक्कतेवर</hl> द्वारा लिखित संगम साहित्य का एक जैन महाकाव्य है। यह राजकुमार जीवक के बारे में है और इसे <hl>मन-नूल (विवाह की पुस्तक)</hl> के रूप में जाना जाता है।" },
                { type: "bullet", text: "नोट: छठी से नौवीं शताब्दी के बीच बड़ोदरा के पास <hl>अकोटा (गुजरात)</hl> एवं पश्चिमी भारतीय क्षेत्र में कांस्य की अधिकांश मूर्तियाँ महावीर, पार्श्वनाथ या आदिनाथ जैसे तीर्थंकरों की बनायी जाती थीं। इसमें तीर्थंकरों को एक सिंहासन पर विराजमान दिखाया गया और ये तीर्थंकर अकेले या तीन से 24 तीर्थंकरों के समूह में प्रस्तुत किए गए। इनके अलावा कुछ प्रमुख तीर्थंकरों की शासन देवियों या यक्षिणियों की नारी प्रतिमाएँ भी बनाई जाने लगीं। <hl>चक्रेश्वरी</hl> आदिनाथ की शासन देवी एवं <hl>अंबिका</hl> नेमिनाथ की शासन देवी है।" },
            ],
            en: [
                { type: "heading", text: "6. Jainism" },
                { type: "bullet", text: "The founder and first Tirthankara of Jainism was <hl>Rishabhadeva</hl>." },
                { type: "bullet", text: "The <hl>Kalpasutra</hl> is the most popular text of the Jain tradition. One part of it describes various events in the lives of the <hl>24 Tirthankaras</hl>, from conception to nirvana. Five major events of their lives are specially presented — <hl>conception, birth, renunciation, attainment of knowledge, and first sermon</hl>." },
                { type: "bullet", text: "The <hl>23rd Tirthankara</hl> of Jainism was <hl>Parshvanath</hl>, son of King <hl>Ashvasena</hl> of the Ikshvaku dynasty of Kashi. He accepted the ascetic life at the age of 30. The teachings given by him were — 1. Non-violence, 2. Always speak the truth, 3. Do not steal, and 4. Do not possess property." },
                { type: "bullet", text: "<hl>Mahavira Swami</hl> was the <hl>24th and last Tirthankara</hl> of Jainism." },
                { type: "bullet", text: "Mahavira was born in <hl>540 BCE</hl> at <hl>Kundagrama (Vaishali)</hl>. His father <hl>Siddhartha</hl> was the chief of the 'Jnatrika clan', and his mother <hl>Trishala</hl> was the sister of Lichchhavi king <hl>Chetak</hl>." },
                { type: "bullet", text: "Mahavira's wife was named <hl>Yashoda</hl> and his daughter was named <hl>Anojja Priyadarshini</hl>." },
                { type: "bullet", text: "Mahavira's childhood name was <hl>Vardhamana</hl>. At the age of 30, after the death of his parents, he accepted the ascetic life with the permission of his elder brother <hl>Nandivardhana</hl>." },
                { type: "bullet", text: "After <hl>12 years</hl> of rigorous penance, Mahavira attained complete knowledge (Kaivalya Jnana) while meditating under a Sal tree on the banks of the <hl>Rijupalika river</hl> near Jrimbhika. From this time on, Mahavira came to be called <hl>Jina (Conqueror), Arhat (Worthy of worship)</hl>, and <hl>Nirgrantha (Free of bonds)</hl>." },
                { type: "heading", text: "Mahavira's Conception Dream" },
                { type: "bullet", text: "At the time of Mahavira's conception, his mother <hl>Trishala</hl> saw a dream of <hl>14 objects</hl>." },
                { type: "bullet", text: "The 14 objects were — <hl>elephant, bull, lion, Goddess Lakshmi, pot, palanquin, lake, small river, fire, flag, garland, heap of jewels, sun, and moon</hl>." },
                { type: "bullet", text: "She spoke to astrologers about her dream. The astrologers told her that she would give birth to a son who would either become a great king or a great saint." },
                { type: "heading", text: "Mahavira's Teachings and Followers" },
                { type: "bullet", text: "The <hl>Uttarayana Sutra</hl> describes Mahavira's teachings, where the code of conduct to be followed by monks is described." },
                { type: "bullet", text: "Mahavira gave his teachings in the <hl>Prakrit (Ardhamagadhi)</hl> language." },
                { type: "bullet", text: "Mahavira's followers were originally called <hl>Nirgrantha</hl>." },
                { type: "bullet", text: "Mahavira's first follower was his son-in-law <hl>Jamil</hl>." },
                { type: "bullet", text: "The first Jain nun was <hl>Champa</hl>, daughter of King Dadhivahana." },
                { type: "heading", text: "Major Jain Tirthankaras and their Symbols" },
                { type: "bullet", text: "<hl>Rishabhadeva (1st)</hl> — Symbol: Bull" },
                { type: "bullet", text: "<hl>Ajitnath (2nd)</hl> — Symbol: Elephant" },
                { type: "bullet", text: "<hl>Sambhava (3rd)</hl> — Symbol: Horse" },
                { type: "bullet", text: "<hl>Suparshva (7th)</hl> — Symbol: Swastika" },
                { type: "bullet", text: "<hl>Shanti (16th)</hl> — Symbol: Deer" },
                { type: "bullet", text: "<hl>Arnath (18th)</hl> — Symbol: Fish" },
                { type: "bullet", text: "<hl>Nami (21st)</hl> — Symbol: Blue Lotus" },
                { type: "bullet", text: "<hl>Aristanemi (22nd)</hl> — Symbol: Conch" },
                { type: "bullet", text: "<hl>Parshva (23rd)</hl> — Symbol: Serpent" },
                { type: "bullet", text: "<hl>Mahavira (24th)</hl> — Symbol: Lion" },
                { type: "bullet", text: "Note: The names of two Jain Tirthankaras — <hl>Rishabhadeva</hl> and <hl>Aristanemi</hl> — are found mentioned in the <hl>Rigveda</hl>. Aristanemi is considered a close relative of Lord Krishna." },
                { type: "bullet", text: "Mahavira divided his disciples into <hl>11 Ganadharas</hl>." },
                { type: "bullet", text: "<hl>Arya Sudharma</hl> was the only Ganadhara who survived even after Mahavira's death and became the first Thera (chief preacher) of Jainism." },
                { type: "bullet", text: "The head of Mahavira's order of nuns was <hl>Chandana</hl>." },
                { type: "heading", text: "Division of Jainism: Shwetambara and Digambara" },
                { type: "bullet", text: "Around <hl>300 BCE</hl>, a severe 12-year famine struck Magadha, due to which <hl>Bhadrabahu</hl> moved to Karnataka along with his disciples. However, some followers stayed back in Magadha with <hl>Sthulabhadra</hl>." },
                { type: "bullet", text: "When Bhadrabahu returned, deep differences arose with the monks of Magadha, as a result of which Jainism split into two sects called <hl>Shwetambara</hl> and <hl>Digambara</hl>." },
                { type: "bullet", text: "Sthulabhadra's disciples came to be called <hl>Shwetambara (those who wear white clothes)</hl>, and Bhadrabahu's disciples were called <hl>Digambara (those who remain unclothed)</hl>." },
                { type: "heading", text: "Differences between Digambara and Shwetambara Sects" },
                { type: "bullet", text: "Digambara: They observe all five vows — truth, non-violence, non-stealing, non-possession, and celibacy." },
                { type: "bullet", text: "Shwetambara: They observe only four vows — truth, non-violence, non-stealing, and non-possession. They do not observe celibacy separately." },
                { type: "bullet", text: "Digambara: This sect accepts the existence of 6 eternal substances — soul (jiva), matter (pudgala), space (akasha), motion (dharma), rest (adharma), and time (kala)." },
                { type: "bullet", text: "Shwetambara: This sect accepts only 5 eternal substances, excluding time (kala) — soul, matter, space, motion, and rest." },
                { type: "bullet", text: "Digambara: In this sect, women cannot become Tirthankaras." },
                { type: "bullet", text: "Shwetambara: In this sect, women can also become Tirthankaras." },
                { type: "bullet", text: "Digambara: They believe Mahavira never married." },
                { type: "bullet", text: "Shwetambara: They believe Mahavira married and had a child." },
                { type: "bullet", text: "Digambara: They believe the 19th Tirthankara Mallinath was male." },
                { type: "bullet", text: "Shwetambara: They believe Mallinath was female." },
                { type: "bullet", text: "Digambara: They say the original Jain Agama texts are lost." },
                { type: "bullet", text: "Shwetambara: They accept the Jain Agama texts as authentic." },
                { type: "bullet", text: "Digambara: They believe one can remain fasting even after attaining Kaivalya (omniscience)." },
                { type: "bullet", text: "Shwetambara: They believe food is still needed even after attaining Kaivalya." },
                { type: "bullet", text: "Digambara: They oppose women attaining liberation within the same life/body." },
                { type: "bullet", text: "Shwetambara: They believe women are entitled to liberation in the same life." },
                { type: "bullet", text: "Digambara: They do not wear white clothes, considering it an obstacle to nirvana (moksha)." },
                { type: "bullet", text: "Shwetambara: They wear white clothes and do not consider it an obstacle to nirvana (moksha)." },
                { type: "heading", text: "Jain Councils" },
                { type: "bullet", text: "The first Jain council was held in <hl>300 BCE</hl> at <hl>Pataliputra</hl>, presided over by <hl>Sthulabhadra</hl>." },
                { type: "bullet", text: "The second Jain council was held in <hl>512 CE</hl> at <hl>Vallabhi (Gujarat)</hl>, presided over by <hl>Kshamashravana</hl>." },
                { type: "heading", text: "Principles of Jainism" },
                { type: "bullet", text: "The three jewels (Triratna) of Jainism are — 1. <hl>Samyak Darshan</hl> (Right Faith), 2. <hl>Samyak Jnana</hl> (Right Knowledge), and 3. <hl>Samyak Charitra</hl> (Right Conduct)." },
                { type: "bullet", text: "In practicing the three jewels, observance of the following <hl>five great vows (Panch Mahavrata)</hl> is essential — <hl>non-violence, truthful speech, non-stealing, non-possession, and celibacy</hl>." },
                { type: "bullet", text: "The principle of donating <hl>four essentials (education, food, medicine, and shelter)</hl> in Jainism helped make it popular." },
                { type: "bullet", text: "Jainism does <hl>not believe in the existence of a creator God</hl>." },
                { type: "bullet", text: "Jainism <hl>believes in the existence of the soul (atma)</hl>. According to Jains, the soul (jiva) is found not only in humans and animals but also in plants, stones, and water. According to Jainism, a soul wanders through the cycle of birth and death based on its karma." },
                { type: "heading", text: "Jain Philosophy: Jiva-Ajiva and the Four States of Existence" },
                { type: "bullet", text: "In Jain philosophy, the four main forms of existence (also called <hl>gatis</hl>) are as follows:" },
                { type: "bullet", text: "1. <hl>Manushya Gati (Human state)</hl>: The existence of humans. According to Jain belief, moksha (liberation from the cycle of birth and death) can only be attained from this state." },
                { type: "bullet", text: "2. <hl>Deva Gati (Celestial state)</hl>: The existence of heavenly beings or gods." },
                { type: "bullet", text: "3. <hl>Tiryancha Gati (Animal/plant state)</hl>: The existence of animals, birds, plants, and microorganisms." },
                { type: "bullet", text: "4. <hl>Naraka Gati (Hellish state)</hl>: The existence of hellish beings." },
                { type: "bullet", text: "When the soul goes beyond these four states and destroys all its karmas, it attains <hl>moksha</hl>." },
                { type: "bullet", text: "According to Jainism, creation is formed of two fundamental elements called <hl>Jiva (soul) and Ajiva (non-soul)</hl>. Jiva is the conscious element, and Ajiva is the non-conscious, inert element (<hl>matter, time, space, motion, and rest</hl>)." },
                { type: "bullet", text: "Mahavira believed in <hl>rebirth and the doctrine of karma</hl>." },
                { type: "bullet", text: "Other names for the Jain doctrine of Saptabhangi (sevenfold predication) are <hl>Syadvada</hl> and <hl>Anekantavada</hl>, which are fundamental principles of Jainism." },
                { type: "bullet", text: "Jainism drew its spiritual ideas from <hl>Samkhya philosophy</hl>. The major festivals of Jainism are: <hl>Mahavira Jayanti, Paryushana Ashtanhika, and Deepavali</hl>." },
                { type: "heading", text: "Kings and Major Sites Associated with Jainism" },
                { type: "bullet", text: "Some kings who followed Jainism were — <hl>Udayin, Vandaraja, Chandragupta Maurya, Kalinga king Kharavela, Rashtrakuta king Amoghavarsha, and the Chandela rulers</hl>." },
                { type: "bullet", text: "At the encouragement of <hl>Chamundaraya</hl>, the commander-in-chief and prime minister of the Ganga dynasty kings of Mysore, a massive granite statue of Bahubali (the <hl>Gomateshwara statue</hl>) was built at <hl>Shravanabelagola</hl>, Karnataka, in the mid-10th century." },
                { type: "bullet", text: "The Gomateshwara statue is in the <hl>Kayotsarga posture</hl>. Bahubali is shown in this posture of penance, unaware of his surroundings. Serpents are shown coiled around his feet, and ants have built mud mounds on him." },
                { type: "bullet", text: "This statue is <hl>18 metres (57 feet)</hl> tall and is carved out of a single rock. It is the world's tallest freestanding monolithic statue." },
                { type: "bullet", text: "The Jain temples at <hl>Mount Abu</hl> in Rajasthan were built by <hl>Vimal Shah</hl>." },
                { type: "bullet", text: "There is a vast Jain pilgrimage site in the <hl>Shatrunjaya Hills</hl> near Palitana in <hl>Kathiawar (Gujarat)</hl>, where dozens of interconnected temples can be seen." },
                { type: "bullet", text: "The Jain temples at <hl>Khajuraho</hl> were built by the <hl>Chandela rulers</hl>." },
                { type: "bullet", text: "The <hl>Sittanavasal caves</hl>, located in the <hl>Pudukkottai</hl> district of modern Tamil Nadu, are associated with Jainism." },
                { type: "bullet", text: "In the post-Mauryan era, <hl>Mathura</hl> was a famous centre of Jainism. Mathura art is associated with Jainism." },
                { type: "heading", text: "Mahavira's Nirvana and Other Facts" },
                { type: "bullet", text: "The biography of the Jain Tirthankaras is found in the <hl>Kalpasutra</hl>, composed by <hl>Bhadrabahu</hl>." },
                { type: "bullet", text: "At the age of <hl>72</hl>, Mahavira attained death (nirvana) in <hl>468 BCE</hl> at <hl>Pavapuri (Rajgir)</hl> in Bihar." },
                { type: "bullet", text: "Mahavira Swami attained nirvana in the royal palace of the Malla king <hl>Sristipala</hl>." },
                { type: "bullet", text: "<hl>Jivaka Chintamani</hl> is a Jain epic of Sangam literature written by the Jain saint <hl>Tiruttakkatevar</hl>. It is about Prince Jivaka and is known as the <hl>Man-Nool ('marriage book')</hl>." },
                { type: "bullet", text: "Note: Between the sixth and ninth centuries, most bronze statues near <hl>Akota (Gujarat)</hl>, close to Vadodara, and in the western Indian region, were made of Tirthankaras such as Mahavira, Parshvanath, or Adinath. The Tirthankaras were shown seated on a throne, either alone or in groups of three to twenty-four. Female images of the guardian goddesses (Shasana Devis) or Yakshinis of some major Tirthankaras also began to be made. <hl>Chakreshwari</hl> is the guardian goddess of Adinath, and <hl>Ambika</hl> is the guardian goddess of Neminath." },
            ]
        },

        "Vedic Civilization": {
            hi: [
                { type: "heading", text: "वैदिक सभ्यता" },
                { type: "bullet", text: "ऋग्वेद सबसे प्राचीन वेद है, जिसकी रचना लगभग <hl>1500-1000 ईसा पूर्व</hl> मानी जाती है।" },
                { type: "bullet", text: "वैदिक काल को दो भागों में बाँटा गया है: <hl>ऋग्वैदिक काल</hl> और <hl>उत्तर वैदिक काल</hl>।" },
                { type: "heading", text: "सामाजिक व्यवस्था" },
                { type: "bullet", text: "समाज <hl>वर्ण व्यवस्था</hl> पर आधारित था — ब्राह्मण, क्षत्रिय, वैश्य, शूद्र।" }
            ],
            en: [
                { type: "heading", text: "Vedic Civilization" },
                { type: "bullet", text: "The Rigveda is the oldest Veda, composed around <hl>1500-1000 BCE</hl>." },
                { type: "bullet", text: "The Vedic Age is divided into two parts: the <hl>Early Vedic Period</hl> and the <hl>Later Vedic Period</hl>." },
                { type: "heading", text: "Social Structure" },
                { type: "bullet", text: "Society was based on the <hl>Varna System</hl> — Brahmin, Kshatriya, Vaishya, Shudra." }
            ]
        }
    }
};