// ═══════════════════════════════════════════════════════════════════
// READING-DATA.JS — Bilingual structured notes for topics (StudyLab)
// ═══════════════════════════════════════════════════════════════════
// RD — READING DATA: Bilingual structured notes, keyed by
// RD[SubjectName][ExactTopicNameFromSD.topics] = { hi: [...], en: [...] }
//
// Block types:
//   { type: "heading", text: "..." }   → bold colored heading
//   { type: "bullet",  text: "..." }   → bullet point line
//   { type: "text",    text: "..." }   → plain paragraph
//
// Highlight any key term/date/name by wrapping it in <hl>...</hl>
// — it renders in the subject's accent color with a soft background.
//
// IMPORTANT: the topic key here must match EXACTLY (same spelling/
// casing) as the string used in SD[Subject].topics below, otherwise
// the "Read" card won't find it and will show "Coming soon".
// ═══════════════════════════════════════════════════════════════════
window.RD = {
    "History": {
        "Sources of Ancient Indian History": {
            hi: [
                { type: "heading", text: "भारत का इतिहास" },
                { type: "bullet", text: "उत्तर में हिमालय से लेकर दक्षिण में समुद्र तक फैला यह उपमहाद्वीप <hl>भारतवर्ष</hl> के नाम से ज्ञात है, जिसे महाकाव्य तथा पुराणों में 'भारतवर्ष' अर्थात् 'भरतों का देश' तथा यहाँ के निवासियों को <hl>भारती</hl> अर्थात् भरत की संतान कहा गया है।" },
                { type: "bullet", text: "<hl>भरत</hl> एक प्राचीन कबीले (उत्तर-पश्चिम में रहने वाले लोगों का एक समूह) का नाम था, इसका उल्लेख ऋग्वेद में भी मिलता है, बाद में इसका प्रयोग देश के लिए होने लगा।" },
                { type: "bullet", text: "प्राचीन भारतीय अपने देश को <hl>जम्बूद्वीप</hl>, अर्थात् जम्बू (जामुन) वृक्षों का द्वीप कहते थे।" },
                { type: "bullet", text: "प्राचीन ईरानी इसे <hl>सिन्धु</hl> नदी के नाम से जोड़ते थे, जिसे वे सिन्धु न कहकर <hl>हिन्दू</hl> कहते थे। यही नाम फिर पूरे पश्चिम में फैल गया और पूरे देश को इसी एक नदी के नाम से जाना जाने लगा।" },
                { type: "bullet", text: "यूनानी इसे '<hl>इंदे</hl>' और अरब इसे <hl>हिन्द</hl> कहते थे। मध्यकाल में इस देश को <hl>हिन्दुस्तान</hl> कहा जाने लगा। यह शब्द भी फारसी शब्द 'हिन्दू' से बना है।" },
                { type: "bullet", text: "यूनानी भाषा के 'इंदे' के आधार पर अंग्रेज इसे '<hl>इंडिया</hl>' कहने लगे।" },
                { type: "bullet", text: "<hl>विंध्य</hl> की पर्वत-शृंखला देश को उत्तर और दक्षिण, दो भागों में बाँटती है। उत्तर में <hl>इंडो यूरोपीय</hl> परिवार की भाषाएँ बोलने वालों की और दक्षिण में <hl>द्रविड़</hl> परिवार की भाषाएँ बोलने वालों का बहुमत है।" },
                { type: "bullet", text: "उत्तर में हिमालय से लेकर दक्षिण में कन्याकुमारी तक; पूर्व में ब्रह्मपुत्र की घाटी से लेकर पश्चिम में सिन्धु पार तक अपना राज्य फैलाने वाले राजे <hl>चक्रवर्तिन</hl> कहलाते थे। इस प्रकार की राजनैतिक एकता कम-से-कम दो बार प्राप्त हुई थी। ईसा पूर्व तीसरी सदी में <hl>अशोक</hl> ने अपना साम्राज्य सुदूर दक्षिणांचल को छोड़कर सारे देश में फैलाया, फिर ईसा की चौथी सदी में <hl>समुद्रगुप्त</hl> की विजय पताका गंगा की घाटी से तमिल देश के छोर तक पहुँची।" },
                { type: "heading", text: "नोट: भारत की जनसंख्या का निर्माण" },
                { type: "bullet", text: "भारत की जनसंख्या का निर्माण जिन प्रमुख नस्लों के लोगों के मिश्रण से हुआ है, वे इस प्रकार हैं—<hl>प्रोटो-आस्ट्रेलायड, पैलियो-मेडिटेरेनियन, काकेशायड, निग्रोयड और मंगोलायड</hl>।" },
                { type: "bullet", text: "भारतीय इतिहास को अध्ययन की सुविधा के लिए तीन भागों में बाँटा गया है—<hl>प्राचीन भारत, मध्यकालीन भारत एवं आधुनिक भारत</hl>।" },
                { type: "bullet", text: "नोट: सबसे पहले इतिहास को तीन भागों में बाँटने का श्रेय जर्मन इतिहासकार <hl>क्रिस्टोफ सेलारियस (1638-1707 ई.)</hl> को है।" },
                { type: "heading", text: "प्राचीन भारत — 1. प्राचीन भारतीय इतिहास के स्रोत" },
                { type: "bullet", text: "प्राचीन भारतीय इतिहास के विषय में जानकारी मुख्यतः <hl>चार स्रोतों</hl> से प्राप्त होती है—1. धर्मग्रंथ 2. ऐतिहासिक ग्रंथ 3. विदेशियों का विवरण व 4. पुरातत्व-संबंधी साक्ष्य।" },
                { type: "heading", text: "धर्मग्रंथ एवं ऐतिहासिक ग्रंथ से मिलनेवाली जानकारी" },
                { type: "bullet", text: "भारत का सर्वप्राचीन धर्मग्रंथ <hl>वेद</hl> है, जिसके संकलनकर्ता महर्षि <hl>कृष्ण द्वैपायन वेदव्यास</hl> को माना जाता है। वेद 'बसुधैव कुटुम्बकम्' का उपदेश देता है। भारतीय परम्परा वेदों को नित्य तथा अपौरुषेय मानती है। वेद चार हैं—<hl>ऋग्वेद, सामवेद, यजुर्वेद एवं अथर्ववेद</hl>। इन चार वेदों को <hl>संहिता</hl> कहा जाता है।" },
                { type: "heading", text: "ऋग्वेद" },
                { type: "bullet", text: "ऋचाओं के क्रमबद्ध ज्ञान के संग्रह को ऋग्वेद कहा जाता है। इसमें <hl>10 मंडल, 1028 सूक्त</hl> (वालखिल्य पाठ के 11 सूक्तों सहित) एवं <hl>10,462 ऋचाएँ</hl> हैं। इस वेद की ऋचाओं के पढ़ने वाले ऋषि को <hl>होतृ</hl> कहते हैं। इस वेद से आर्य की राजनीतिक प्रणाली, इतिहास एवं ईश्वर की महिमा के बारे में जानकारी मिलती है।" },
                { type: "bullet", text: "<hl>विश्वामित्र</hl> द्वारा रचित ऋग्वेद के तीसरे मंडल में सूर्य देवता सावित्री को समर्पित प्रसिद्ध <hl>गायत्री मंत्र</hl> है। इसके 9वें मंडल में देवता <hl>सोम</hl> का उल्लेख है।" },
                { type: "bullet", text: "इसके 8वें मंडल की हस्तलिखित ऋचाओं को <hl>खिल</hl> कहा जाता है।" },
                { type: "bullet", text: "ऋग्वेद का सबसे बड़ा <hl>10वाँ मंडल</hl> है। इसमें नदिस्तुति सूक्त (नदियों की प्रशंसा), पुरुषसूक्त (वैदिक समाजशास्त्र), नासदीय सूक्त (ब्रह्मांड के सृजन से संबंधित अनुमान), सूर्य सूक्त, विवाह श्लोक आदि सम्मिलित हैं।" },
                { type: "bullet", text: "चातुर्वर्ण्य समाज की कल्पना का आदि स्रोत (ऋग्वेद के 10वें मंडल में वर्णित) <hl>पुरुषसूक्त</hl> है, जिसके अनुसार चार वर्ण (ब्राह्मण, क्षत्रिय, वैश्य तथा शूद्र) आदि पुरुष ब्रह्मा के क्रमशः मुख, भुजाओं, जंघाओं और चरणों से उत्पन्न हुए।" },
                { type: "bullet", text: "नोट: धर्मसूत्र चार प्रमुख जातियों की स्थितियों, व्यवसायों, दायित्वों, कर्तव्यों तथा विशेषाधिकारों में स्पष्ट विभेद करता है।" },
                { type: "bullet", text: "ऋग्वेद के कई परिच्छेदों में प्रयुक्त <hl>अघन्य</hl> (जिसका वध नहीं किया जाता है) शब्द का संबंध गाय से है।" },
                { type: "bullet", text: "ऋग्वेद में <hl>ब्रह्म</hl> का उल्लेख तो है, किन्तु <hl>आत्मा</hl> का नहीं।" },
                { type: "heading", text: "ईसा पूर्व एवं ईस्वी" },
                { type: "bullet", text: "वर्तमान में प्रचलित <hl>ग्रेगोरियन कैलेंडर</hl> (ईसाई कैलेंडर/जूलियन कैलेंडर) ईसाई धर्मगुरु ईसा मसीह के जन्म-वर्ष (कल्पित) पर आधारित है। ईसा मसीह के जन्म के पहले के समय को <hl>ईसा पूर्व (B.C.)</hl> कहा जाता है। ईसा पूर्व में वर्षों की गिनती उल्टी दिशा में होती है, जैसे महात्मा बुद्ध का जन्म <hl>563 ईसा पूर्व</hl> में एवं मृत्यु <hl>483 ईसा पूर्व</hl> में हुआ।" },
                { type: "bullet", text: "वर्तमान में ई. पू. (BC) की जगह <hl>सा.सं. पूर्व/BCE</hl> का एवं ई. (AD) की जगह <hl>सा. सं./CE (Common Era)</hl> का प्रयोग किया जाता है।" },
                { type: "bullet", text: "ईसा मसीह की जन्म-तिथि से आरंभ हुआ सन्, ईसवी सन् कहलाता है, इसके लिए संक्षेप में <hl>ई.</hl> लिखा जाता है। ई. को लैटिन भाषा के शब्द <hl>A.D. (Anno Domini)</hl> में भी लिखा जाता है, जिसका शाब्दिक अर्थ है— In the year of lord (Jesus Christ)।" },
                { type: "bullet", text: "<hl>विन्सेंट आर्थर स्मिथ</hl> ने प्राचीन भारत का पहला सुव्यवस्थित इतिहास <hl>'अर्ली हिस्ट्री ऑफ इंडिया'</hl> 1904 में तैयार किया। इस पुस्तक के एक-तिहाई भाग में केवल सिकन्दर का आक्रमण वर्णित है। इसमें भारत को स्वेच्छाचारी शासन वाला देश कहा गया है, जिसे ब्रिटिश शासन की स्थापना से पहले कभी राजनीतिक एकता का अनुभव नहीं हुआ था।" },
                { type: "bullet", text: "वामनावतार के तीन पगों के आख्यान का प्राचीनतम स्रोत <hl>ऋग्वेद</hl> है।" },
                { type: "heading", text: "वामन अवतार" },
                { type: "bullet", text: "<hl>वामन अवतार</hl> भगवान विष्णु के पहले ऐसे अवतार थे जो मानव रूप में प्रकट हुए थे। उनके पिता <hl>कश्यप ऋषि</hl> एवं माता <hl>अदिति</hl> थी। वे बौने ब्राह्मण के रूप में जन्मे थे। भागवत पुराण के अनुसार वामन अवतार का उद्देश्य भगवान विष्णु द्वारा <hl>इन्द्र</hl> को पुनः स्वर्गलोक पर अधिकार दिलाना था। वामन भगवान को दक्षिण भारत में <hl>उपेन्द्र</hl> के नाम से जाना जाता है।" },
                { type: "bullet", text: "ऋग्वेद में इन्द्र के लिए <hl>250</hl> तथा अग्नि के लिए <hl>200</hl> ऋचाओं की रचना की गयी है।" },
                { type: "bullet", text: "प्राचीन इतिहास के साधन के रूप में वैदिक साहित्य में ऋग्वेद के बाद <hl>शतपथ ब्राह्मण</hl> का स्थान है।" },
                { type: "bullet", text: "नोट: यूनेस्को ने पुणे के भंडारकर ओरिएंटल रिसर्च इंस्टीट्यूट में संरक्षित ऋग्वेद की <hl>30 पांडुलिपियों</hl> को वर्ष <hl>2007</hl> में मेमोरी ऑफ द वर्ल्ड रजिस्टर में शामिल किया है।" },
                { type: "heading", text: "सामवेद" },
                { type: "bullet", text: "'साम' का शाब्दिक अर्थ है <hl>गान</hl>। इस वेद में मुख्यतः यज्ञों के अवसर पर गाये जाने वाले ऋचाओं (मन्त्रों) का संकलन है। इसके पाठकर्ता को <hl>उद्गातृ</hl> कहते हैं। इसका संकलन ऋग्वेद पर आधारित है। इसमें <hl>1810 सूक्त</hl> हैं जो प्रायः ऋग्वेद से लिये गए हैं।" },
                { type: "bullet", text: "इसे <hl>भारतीय संगीत का जनक</hl> कहा जाता है।" },
                { type: "heading", text: "यजुर्वेद" },
                { type: "bullet", text: "सस्वर पाठ के लिए मंत्रों तथा बलि के समय अनुपालन के लिए नियमों का संकलन यजुर्वेद कहलाता है। इसके पाठकर्ता को <hl>अध्वर्यु</hl> कहते हैं।" },
                { type: "bullet", text: "यजुर्वेद में यज्ञों के नियमों एवं विधि-विधानों का संकलन मिलता है।" },
                { type: "bullet", text: "इसमें बलिदान विधि का भी वर्णन है।" },
                { type: "bullet", text: "यह एक ऐसा वेद है जो <hl>गद्य एवं पद्य</hl> दोनों में है।" },
                { type: "bullet", text: "नोट: यजुर्वेद तथा सामवेद में किसी भी विशिष्ट ऐतिहासिक घटना का वर्णन नहीं मिलता।" },
                { type: "heading", text: "अथर्ववेद" },
                { type: "bullet", text: "<hl>अथर्व ऋषि</hl> द्वारा रचित इस वेद में कुल <hl>20 काण्ड, 36 प्रपाठक, 731 सूक्त</hl> और लगभग <hl>5987 मंत्र</hl> हैं। इसे <hl>ब्रह्मवेद, अथर्वाड़िगिरस वेद, भिषग्वेद और क्षत्रवेद</hl> जैसे नामों से भी जाना जाता है।" },
                { type: "bullet", text: "अथर्ववेद में धर्म, अर्थ, काम और मोक्ष (<hl>पुरुषार्थ चतुष्ट्य</hl>) के सभी अंगों का वर्णन है।" },
                { type: "bullet", text: "<hl>पृथ्वीसूक्त</hl> अथर्ववेद का प्रतिनिधि सूक्त माना जाता है, जो अथर्ववेद के <hl>12वें काण्ड</hl> में है। इसमें राष्ट्रीय भावना का उल्लेख मिलता है।" },
                { type: "bullet", text: "इसमें मानव जीवन के सभी पक्षों—गृह निर्माण, कृषि की उन्नति, व्यापारिक मार्गों की खोज, रोग निवारण, विवाह तथा प्रणय गीतों, राजभक्ति, राजा का चुनाव, वनस्पतियों एवं औषधियों, शाप, वशीकरण, प्रायश्चित, मातृभूमि महात्म्य आदि का विवरण दिया गया है। कुछ मंत्रों में जादू-टोने का भी वर्णन है।" },
                { type: "bullet", text: "अथर्ववेद में <hl>परीक्षित</hl> को कुरुओं का राजा और मृत्युलोक का देवता बताया गया है। इसमें कुरु देश की समृद्धि का अच्छा चित्रण मिलता है।" },
                { type: "bullet", text: "अथर्ववेद में मगध के लोगों को <hl>व्रात्य</hl> कहा गया है जो प्राकृत भाषा बोलते थे।" },
                { type: "bullet", text: "अथर्ववेद में <hl>एकराट</hl> सर्वोच्च शासक को कहा गया है।" },
                { type: "bullet", text: "<hl>क्षेत्र-पली</hl> (खेत की स्वामिनी) शब्द अथर्ववेद से उद्भूत है।" },
                { type: "bullet", text: "इसमें सभा एवं समिति को प्रजापति की दो पुत्रियाँ कहा गया है।" },
                { type: "bullet", text: "वेदों की भी कई शाखाएँ हैं। <hl>शाकल शाखा</hl> ऋग्वेद से जुड़ी एकमात्र जीवित शाखा है। यजुर्वेद को <hl>शुक्ल यजुर्वेद</hl> और <hl>कृष्ण यजुर्वेद</hl> दो शाखाओं में बाँटा गया है। माध्यन्दिन और काण्व शुक्ल यजुर्वेद (वाजसनेय संहिता) की शाखाएँ हैं। काठक, कणिष्ठल मैत्रायणी और तैत्तिरीय कृष्ण यजुर्वेद से जुड़ी शाखाएँ हैं। कौथुम, राणायनीय और जैमीनीय सामवेद की शाखाएँ हैं। अथर्ववेद की नौ शाखाएँ थीं—पैप्पलाद, तौद, मौद, शौनक, जाजल, जलद, ब्रह्मवद, देवदर्श एवं चारण वैद्य। इनमें <hl>शौनक संहिता</hl> पूर्णरूप से उपलब्ध है, पैप्पलाद संहिता अभी अपूर्ण उपलब्ध है।" },
                { type: "bullet", text: "नोट: सबसे प्राचीन वेद <hl>ऋग्वेद</hl> एवं सबसे बाद का वेद <hl>अथर्ववेद</hl> है।" },
                { type: "heading", text: "ब्राह्मण, आरण्यक तथा उपनिषद" },
                { type: "bullet", text: "संहिता के पश्चात् <hl>ब्राह्मणों, आरण्यकों तथा उपनिषदों</hl> का स्थान है। इनसे उत्तर वैदिक कालीन समाज एवं संस्कृति के विषय में जानकारी प्राप्त होती है।" },
                { type: "bullet", text: "ब्राह्मण ग्रंथ वैदिक संहिताओं की व्याख्या करने के लिए गद्य में लिखे गए हैं। ऋग्वेद का ब्राह्मण ग्रंथ <hl>ऐतरेय व कौषीतकी</hl> है, सामवेद का <hl>पंचविंश</hl>, यजुर्वेद का <hl>तैत्तिरीय व शतपथ</hl>, और अथर्ववेद का <hl>गोपथ</hl> है।" },
                { type: "bullet", text: "इन ब्राह्मण ग्रंथों से हमें <hl>परीक्षित के बाद और बिम्बसार के पूर्व</hl> की घटनाओं का ज्ञान प्राप्त होता है।" },
                { type: "bullet", text: "<hl>ऐतरेय</hl> में राज्याभिषेक के नियम एवं कुछ प्राचीन राजाओं के नाम दिए गए हैं।" },
                { type: "bullet", text: "<hl>शतपथ</hl> में गंधार, शल्य, कैकय, कुरु, पंचाल, कोसल, विदेह आदि राजाओं का उल्लेख मिलता है।" },
                { type: "bullet", text: "आरण्यक में यज्ञ से जुड़े कर्मकाण्डों की दार्शनिक और प्रतीकात्मक अभिव्यक्ति है।" },
                { type: "bullet", text: "उपनिषदों की संख्या <hl>108</hl> है, जिनमें <hl>13</hl> को मूलभूत उपनिषदों की श्रेणी में रखा गया है। इसमें यज्ञ से जुड़े दार्शनिक विचार, ब्रह्माण्ड, शरीर, आत्मा तथा ब्रह्म की व्याख्या की गई है।" },
                { type: "bullet", text: "स्त्री की सर्वाधिक गिरी हुई स्थिति <hl>मैत्रेयनी संहिता</hl> में प्राप्त होती है, जिसमें जुआ और शराब की भाँति स्त्री को पुरुष का तीसरा मुख्य दोष बताया गया है।" },
                { type: "bullet", text: "शतपथ ब्राह्मण में स्त्री को पुरुष की <hl>अर्धांगिनी</hl> कहा गया है।" },
                { type: "bullet", text: "<hl>जावालोपनिषद्</hl> में चारों आश्रमों का उल्लेख मिलता है।" },
                { type: "bullet", text: "स्मृतिग्रंथों में सबसे प्राचीन एवं प्रामाणिक <hl>मनुस्मृति</hl> मानी जाती है। यह <hl>शुंग काल</hl> का मानक ग्रंथ है।" },
                { type: "bullet", text: "<hl>नारद स्मृति</hl> गुप्त युग के विषय में जानकारी प्रदान करता है। यह विशुद्ध रूप से न्याय संबंधी ग्रंथ है, जिसमें कुल <hl>18 प्रकरण और 1028 श्लोक</hl> हैं। इसे प्राचीन भारत का विधिग्रंथ कहा जा सकता है।" },
                { type: "heading", text: "वेदांग एवं सूत्र" },
                { type: "bullet", text: "वेदों को भली-भाँति समझने के लिए <hl>छह वेदांगों</hl> की रचना हुई—शिक्षा (शुद्ध उच्चारण शास्त्र), कल्प (कर्मकाण्डीय विधि), निरुक्त (शब्दों की व्युत्पत्ति का शास्त्र), व्याकरण, छन्द व ज्योतिष।" },
                { type: "bullet", text: "वैदिक साहित्य को अक्षुण्ण बनाए रखने के लिए सूत्र साहित्य का प्रणयन किया गया। <hl>कल्पसूत्र</hl> मुख्यतः चार प्रकार के होते हैं—1. श्रौत सूत्र (यज्ञविधि) 2. गृहसूत्र (गृहस्थ धर्म) 3. धर्मसूत्र (धार्मिक आचार) 4. शुल्वसूत्र (यज्ञ वेदियों की ज्यामिति)।" },
                { type: "bullet", text: "प्रमुख सूत्रकार हैं: <hl>गौतम, बौधायन, आपस्तम्ब, वशिष्ठ</hl> (धर्मसूत्र); <hl>सांख्यायन, आश्वलायन</hl> (गृह्यसूत्र); <hl>जैमिनी</hl> (मीमांसा सूत्र); <hl>पाणिनि</hl> (व्याकरण सूत्र अष्टाध्यायी)।" },
                { type: "bullet", text: "सूत्रों में <hl>गौतम धर्मसूत्र</hl> सबसे प्राचीन माना गया है।" },
                { type: "heading", text: "पुराण" },
                { type: "bullet", text: "भारतीय ऐतिहासिक कथाओं का सबसे अच्छा क्रमबद्ध विवरण पुराणों में मिलता है। इसके रचयिता <hl>लोमहर्ष अथवा इनके पुत्र उग्रश्रवा</hl> माने जाते हैं। इनकी संख्या <hl>18</hl> हैं, जिनमें से केवल पाँच—<hl>मत्स्य, वायु, विष्णु, ब्राह्माण्ड एवं भागवत</hl> में ही राजाओं की वंशावली पायी जाती है।" },
                { type: "bullet", text: "<hl>विष्णु पुराण</hl> में मौर्य वंश, <hl>मत्स्य पुराण</hl> में आन्ध्र सातवाहन, और <hl>वायु पुराण</hl> में गुप्त वंश की वंशावली मिलती है।" },
                { type: "bullet", text: "अधिकतर पुराण सरल संस्कृत श्लोक में लिखे गये हैं। स्त्रियाँ तथा शूद्र, जिन्हें वेद पढ़ने की अनुमति नहीं थी, वे भी पुराण सुन सकते थे। पुराणों का पाठ पुजारी मंदिरों में किया करते थे।" },
                { type: "bullet", text: "नोट: पुराणों में <hl>मत्स्यपुराण</hl> सबसे प्राचीन एवं प्रामाणिक है।" },
                { type: "bullet", text: "सामाजिक एवं सांस्कृतिक दृष्टि से <hl>अग्निपुराण</hl> का काफी महत्व है जिसमें राजतन्त्र के साथ-साथ कृषि संबंधी विवरण भी दिया गया है।" },
                { type: "bullet", text: "<hl>कालिका पुराण</hl> हिन्दू धर्म के 18 उपपुराणों में से एक माना जाता है। यह हिन्दू धर्म के <hl>शाक्त संप्रदाय</hl> से संबंधित है।" },
                { type: "bullet", text: "नोट: उपनिषदों की रचना पुराणों से पहले हुई थी।" },
                { type: "heading", text: "बौद्ध, जैन एवं अन्य साहित्य" },
                { type: "bullet", text: "<hl>जातक</hl> में बुद्ध की पूर्वजन्म की कहानी वर्णित है। हीनयान का प्रमुख ग्रंथ <hl>कथावत्थु</hl> (पालि भाषा में) है, जिसकी रचना स्थविर <hl>मोग्गलिपुत्त तिस्स</hl> ने लगभग तीसरी शताब्दी ईसापूर्व की थी।" },
                { type: "bullet", text: "जैन साहित्य को <hl>आगम</hl> कहा जाता है। जैनधर्म का प्रारंभिक इतिहास '<hl>कल्पसूत्र</hl>' से ज्ञात होता है, जिसके रचयिता <hl>भद्रबाहु</hl> माने जाते हैं। इसमें तीर्थंकरों (विशेषकर पार्श्वनाथ और महावीर स्वामी) के जीवनचरित का वर्णन है। पर्युषण पर्व के दौरान जैन साधु-साध्वी इसका पाठ और व्याख्या करते हैं। जैन ग्रंथ <hl>भगवती सूत्र</hl> में महावीर के जीवन-कृत्यों का विवरण मिलता है।" },
                { type: "bullet", text: "नोट: जैन ग्रंथों की रचना प्राकृत भाषा में हुई थी। ईसा की छठी सदी में गुजरात के <hl>वल्लभी</hl> नगर में इन्हें अंतिम रूप से संकलित किया गया।" },
                { type: "bullet", text: "<hl>अर्थशास्त्र</hl> के लेखक <hl>चाणक्य (कौटिल्य या विष्णुगुप्त)</hl> हैं। इसमें <hl>15 अधिकरण, 180 प्रकरण तथा 4000 श्लोक</hl> हैं। यह एक विधि ग्रंथ है, जिससे मौर्यकालीन इतिहास की जानकारी प्राप्त होती है।" },
                { type: "bullet", text: "नोट: <hl>शामशास्त्री</hl> ने 1905 में अर्थशास्त्र को खोजा और 1909 में पहली बार इसका संस्कृत संस्करण प्रकाशित किया। मूल रूप में अर्थशास्त्र की पांडुलिपियाँ ताड़ के पत्तों पर ग्रंथलिपि में लिखी हुई थीं।" },
                { type: "bullet", text: "संस्कृत साहित्य में ऐतिहासिक घटनाओं को क्रमबद्ध लिखने का सर्वप्रथम प्रयास <hl>कल्हण</hl> के द्वारा किया गया। कल्हण द्वारा रचित पुस्तक <hl>राजतरंगिणी</hl> (राजाओं की नदी) है, जिसमें <hl>आठ सर्ग</hl> (तरंग) हैं। इसमें प्रारंभ से लेकर 12वीं सदी तक के कश्मीर के शासकों का वर्णन है।" },
                { type: "bullet", text: "अरबों की सिंध-विजय का वृत्तांत <hl>चचनामा</hl> (या फतेहनामा) मूलरूप से अरबी भाषा में थी, जिसका फारसी में अनुवाद 1226 में <hl>अली बिन अबू बकर कूफी</hl> ने किया; इसके बाद <hl>मिर्जा कालीचबेग</hl> ने वर्ष 1900 में इसे अंग्रेजी एवं सिन्धी में अनुवाद किया।" },
                { type: "bullet", text: "'<hl>अष्टाध्यायी</hl>' (संस्कृत भाषा व्याकरण की प्रथम पुस्तक) के लेखक <hl>पाणिनि</hl> हैं, जिनका समय लगभग 5वीं शताब्दी सामान्य संवत पूर्व (नंदों का काल) माना जाता है।" },
                { type: "bullet", text: "नोट: अष्टाध्यायी में <hl>3996 सूत्रों</hl> के माध्यम से संस्कृत व्याकरण के नियमों को संकलित किया गया है। इसमें पहली बार '<hl>लिपि</hl>' शब्द का प्रयोग हुआ है।" },
                { type: "bullet", text: "कल्हण की <hl>गार्गी-संहिता</hl> एक ज्योतिष ग्रंथ है, फिर भी इसमें भारत पर होने वाले यवन आक्रमण का उल्लेख मिलता है।" },
                { type: "bullet", text: "<hl>पतंजलि</hl> पुष्यमित्र शुंग के पुरोहित थे, इनके <hl>महाभाष्य</hl> से शुंगों के इतिहास का पता चलता है।" },
                { type: "bullet", text: "महाभारत में, प्राग्ज्योतिष (आधुनिक असम) के शासक <hl>भगदत्त</hl> का उल्लेख कौरवों की ओर से लड़ने वाले योद्धा के रूप में किया गया है।" },
                { type: "heading", text: "विदेशी यात्रियों से मिलनेवाली जानकारी — A. यूनानी-रोमन लेखक" },
                { type: "bullet", text: "<hl>टेसियस</hl>: यह ईरान का राजवैद्य था। भारत के संबंध में इसका विवरण आश्चर्यजनक कहानियों से परिपूर्ण होने के कारण अविश्वसनीय है।" },
                { type: "bullet", text: "<hl>हेरोडोटस</hl>: इसे 'इतिहास का पिता' कहा जाता है। इसने अपनी पुस्तक हिस्टोरिका में 5वीं शताब्दी ईसा पूर्व के भारत-फारस संबंध का वर्णन किया है, परन्तु इसका विवरण भी अनुश्रुतियों एवं अफवाहों पर आधारित है।" },
                { type: "bullet", text: "सिकन्दर के साथ आनेवाले लेखकों में <hl>नियाखिस, आनेसिक्रटस तथा आरिस्टोबुलस</hl> के विवरण अधिक प्रामाणिक एवं विश्वसनीय हैं।" },
                { type: "bullet", text: "<hl>मेगास्थनीज</hl>: यह सेल्युकस निकेटर का राजदूत था, जो चन्द्रगुप्त मौर्य के राजदरबार में आया था। इसने अपनी पुस्तक <hl>इण्डिका</hl> में मौर्य युगीन समाज एवं संस्कृति के विषय में लिखा है।" },
                { type: "bullet", text: "<hl>डाइमेकस</hl>: यह सीरियन नरेश आन्तियोकस का राजदूत था, जो बिन्दुसार के राजदरबार में आया था।" },
                { type: "bullet", text: "<hl>डायोनिसियस</hl>: यह मिस्र नरेश टॉलमी फिलेडेल्फस का राजदूत था, जो अशोक के राजदरबार में आया था।" },
                { type: "bullet", text: "<hl>टॉलमी</hl>: इसने दूसरी शताब्दी में 'भारत का भूगोल' नामक पुस्तक लिखी।" },
                { type: "bullet", text: "<hl>प्लिनी</hl>: इसने प्रथम शताब्दी में 'नेचुरल हिस्ट्री' नामक पुस्तक लिखी, जिसमें भारतीय पशुओं, पेड़-पौधों, खनिज-पदार्थों आदि के बारे में विवरण मिलता है।" },
                { type: "bullet", text: "<hl>पेरीप्लस ऑफ द इरिथ्रयन-सी</hl>: इस पुस्तक के लेखक के बारे में जानकारी नहीं है। यह लेखक करीब 80 ई. में हिन्द महासागर की यात्रा पर आया था और उस समय के भारत के बन्दरगाहों तथा व्यापारिक वस्तुओं के बारे में जानकारी दी है।" },
                { type: "heading", text: "B. चीनी लेखक" },
                { type: "bullet", text: "<hl>फाहियान</hl>: यह चीनी यात्री गुप्त नरेश <hl>चन्द्रगुप्त द्वितीय</hl> के दरबार में आया था। इसने मध्यप्रदेश के समाज एवं संस्कृति के बारे में वर्णन किया और जनता को सुखी एवं समृद्ध बताया। यह <hl>14 वर्षों</hl> तक भारत में रहा।" },
                { type: "bullet", text: "<hl>संयुगन</hl>: यह <hl>518 ई.</hl> में भारत आया। इसने अपने तीन वर्षों की यात्रा में बौद्ध धर्म की प्राप्तियाँ एकत्रित कीं।" },
                { type: "bullet", text: "<hl>ह्वेनसाँग</hl>: यह हर्षवर्धन के शासनकाल में <hl>629 ई.</hl> में चीन से भारतवर्ष के लिए प्रस्थान किया और लगभग एक वर्ष की यात्रा के बाद भारतीय राज्य कपिशा पहुँचा। भारत में <hl>15 वर्षों</hl> तक ठहरकर <hl>645 ई.</hl> में चीन लौट गया। वह बिहार के <hl>नालंदा विश्वविद्यालय</hl> में अध्ययन करने तथा भारत से बौद्ध ग्रंथों को एकत्र कर ले जाने के लिए आया था। इसका भ्रमण वृत्तांत <hl>सि-यू-की</hl> नाम से प्रसिद्ध है, जिसमें 138 देशों का वर्णन मिलता है। इसके अनुसार सिन्ध का राजा शूद्र था। ह्वेनसांग ने बुद्ध की प्रतिमा के साथ-साथ सूर्य और शिव की प्रतिमाओं का भी पूजन किया था।" },
                { type: "bullet", text: "नोट: ह्वेनसाँग के अध्ययन के समय नालंदा विश्वविद्यालय के कुलपति आचार्य <hl>शीलभद्र</hl> थे। यह विश्वविद्यालय बौद्ध दर्शन के लिए प्रसिद्ध था।" },
                { type: "bullet", text: "<hl>इत्सिंग</hl>: यह 7वीं शताब्दी के अन्त में भारत आया। इसने नालंदा विश्वविद्यालय, विक्रमशिला विश्वविद्यालय तथा अपने समय के भारत का वर्णन किया है।" },
                { type: "heading", text: "C. अरबी लेखक" },
                { type: "bullet", text: "<hl>अलबरुनी</hl>: यह महमूद गजनवी के साथ भारत आया था। वह ख्वारिज्म या खीव (आधुनिक तुर्कमेनिस्तान) का रहने वाला था। अरबी में लिखी गई उसकी कृति '<hl>किताब-उल-हिन्द या तहकीक-ए-हिन्द (भारत की खोज)</hl>' आज भी इतिहासकारों के लिए एक महत्वपूर्ण स्रोत है। इसमें राजपूत कालीन समाज, धर्म, रीति-रिवाज, राजनीति आदि पर सुन्दर प्रकाश डाला गया है।" },
                { type: "bullet", text: "<hl>इब्न बतूता</hl>: इसके द्वारा अरबी भाषा में लिखा गया यात्रा-वृतांत '<hl>रेहला</hl>' 14वीं शताब्दी में भारतीय उपमहाद्वीप के सामाजिक तथा सांस्कृतिक जीवन के विषय में बहुत ही प्रचुर जानकारी देता है। 1333 ई. में दिल्ली पहुँचने पर इसकी विद्वत्ता से प्रभावित होकर सुल्तान <hl>मुहम्मद बिन तुगलक</hl> ने उसे दिल्ली का काजी नियुक्त किया।" },
                { type: "heading", text: "D. अन्य लेखक" },
                { type: "bullet", text: "<hl>तारानाथ</hl>: यह एक तिब्बती लेखक था। इसने '<hl>कंग्युर</hl>' तथा '<hl>तंग्युर</hl>' नामक ग्रंथ की रचना की, जिनसे भारतीय इतिहास के बारे में जानकारी मिलती है।" },
                { type: "bullet", text: "<hl>मार्कोपोलो</hl>: यह 13वीं शताब्दी के अन्त में <hl>पाण्ड्य</hl> देश की यात्रा पर आया था। इसका विवरण पाण्ड्य इतिहास के अध्ययन के लिए उपयोगी है।" },
                { type: "heading", text: "पुरातत्व संबंधी साक्ष्य से मिलनेवाली जानकारी" },
                { type: "bullet", text: "भारतीय पुरातत्वशास्त्र का पितामह (Father of Indian Archaeology) <hl>सर अलेक्जेण्डर कनिंघम</hl> को कहा जाता है।" },
                { type: "bullet", text: "<hl>अलेक्जेंडर री, ए.एच. लोंगहर्स्ट, रावर्ट सेवेल, जेम्स बर्गेस, वाल्टर इलियट</hl> ये सभी भारत के पुरातात्विक स्थलों के उत्खनन से संबंधित हैं। इन लोगों ने भड़ी प्रोलू, घंटासला, अमरावती आदि स्थलों की खुदाई की।" },
                { type: "bullet", text: "<hl>1400 ई.पू.</hl> के अभिलेख '<hl>बोगाज-कोई</hl>' (एशिया माइनर) से वैदिक देवता मित्र, वरुण, इन्द्र और नासत्य (अश्विनी कुमार) के नाम मिलते हैं।" },
                { type: "bullet", text: "मध्य भारत में <hl>भागवत धर्म (वैष्णव संप्रदाय)</hl> विकसित होने का प्रमाण तक्षशिला के इंडो-ग्रीक राजा एन्टियाल्किडस के राजदूत '<hl>हेलियोडोरस</hl>' के वेसनगर (विदिशा) गरुड़ स्तम्भ लेख से प्राप्त होता है। हेलियोडोरस शुंग वंश के राजा भागभद्र के दरबार में आया था।" },
                { type: "bullet", text: "सर्वप्रथम '<hl>भारतवर्ष</hl>' का जिक्र <hl>हाथीगुम्फा अभिलेख</hl> में है।" },
                { type: "bullet", text: "सर्वप्रथम दुर्भिक्ष की जानकारी देनेवाला अभिलेख <hl>सौहगौरा अभिलेख</hl> है। इसमें संकट काल में उपयोग हेतु खाद्यान्न सुरक्षित रखने का भी उल्लेख है।" },
                { type: "bullet", text: "सर्वप्रथम भारत पर होनेवाले <hl>हूण आक्रमण</hl> की जानकारी <hl>भीतरी स्तंभ लेख</hl> से प्राप्त होती है।" },
                { type: "bullet", text: "<hl>सती-प्रथा</hl> का पहला लिखित साक्ष्य <hl>एरण अभिलेख</hl> (शासक भानुगुप्त) से प्राप्त होती है।" },
                { type: "bullet", text: "<hl>सातवाहन</hl> राजाओं का पूरा इतिहास उनके अभिलेखों के आधार पर ही लिखा गया है।" },
                { type: "bullet", text: "<hl>वत्सभट्टि</hl> द्वारा संस्कृत में लिखे <hl>मंदसौर (दशपुर) अभिलेख</hl> में रेशम बुनकरों की एक श्रेणी द्वारा सूर्य मंदिर के निर्माण का उल्लेख है। यह अभिलेख मुख्यरूप से कुमारगुप्त और बंधुवर्मा से संबंधित है।" },
                { type: "bullet", text: "कश्मीरी नवपाषाणिक पुरास्थल <hl>बुर्जहोम</hl> से गर्ताबास (गड्ढा घर) का साक्ष्य मिला है। यहाँ मनुष्य के साथ उसके पालतू कुत्ते को भी दफनाने की प्रथा प्रचलित थी।" },
                { type: "bullet", text: "नोट: पुरास्थल उस स्थान को कहते हैं जहाँ औजार, बर्तन और इमारतों जैसी वस्तुओं के अवशेष मिलते हैं।" },
                { type: "bullet", text: "प्राचीनतम सिक्कों को <hl>आहत सिक्के</hl> कहा जाता है, इसी को साहित्य में <hl>कार्षापण</hl> कहा गया है।" },
                { type: "bullet", text: "सर्वप्रथम सिक्कों पर लेख लिखने का कार्य <hl>यवन शासकों</hl> ने किया।" },
                { type: "heading", text: "महत्वपूर्ण अभिलेख" },
                { type: "bullet", text: "<hl>हाथीगुम्फा अभिलेख</hl> (तिथि रहित, प्राकृत भाषा) — शासक: <hl>कलिंग राज खारवेल</hl>। इस अभिलेख में पहली बार 'भारत वर्ष' शब्द का लिखित उल्लेख मिलता है।" },
                { type: "bullet", text: "<hl>जूनागढ़ (गिरनार) अभिलेख</hl> (संस्कृत) — शासक: <hl>रुद्रदामन प्रथम</hl>। इसे संस्कृत में पहला लंबा शिलालेख जारी करने का श्रेय दिया जाता है। इसमें सुदर्शन झील के पुनरुद्धार का उल्लेख है।" },
                { type: "bullet", text: "<hl>नासिक अभिलेख</hl> (प्राकृत) — शासिका: <hl>गौतमी बलश्री</hl>।" },
                { type: "bullet", text: "<hl>प्रयाग स्तम्भ लेख</hl> (संस्कृत) — शासक: <hl>समुद्रगुप्त</hl>।" },
                { type: "bullet", text: "<hl>ऐहोल अभिलेख</hl> (संस्कृत) — शासक: <hl>पुलकेशिन-II</hl>।" },
                { type: "bullet", text: "<hl>मन्दसौर (सोंधनी) अभिलेख</hl> (संस्कृत) — शासक: मालवा नरेश <hl>यशोधर्मन</hl>।" },
                { type: "bullet", text: "<hl>ग्वालियर अभिलेख</hl> (संस्कृत) — शासक: प्रतिहार नरेश <hl>भोज</hl>।" },
                { type: "bullet", text: "<hl>भितरी एवं जूनागढ़ अभिलेख</hl> (संस्कृत) — शासक: <hl>स्कन्दगुप्त</hl>।" },
                { type: "bullet", text: "<hl>देवपाड़ा अभिलेख</hl> (संस्कृत) — शासक: बंगाल शासक <hl>विजयसेन</hl>।" },
                { type: "bullet", text: "अभिलेखों का अध्ययन <hl>पुरालेखशास्त्र (इपीग्राफी)</hl> कहलाता है, और पुराने दस्तावेजों की प्राचीन तिथि के अध्ययन को <hl>पुरालिपिशास्त्र</hl> कहते हैं। सबसे अधिक अभिलेख मैसूर में संगृहीत हैं। सबसे पुराने अभिलेख हड़प्पा संस्कृति की मोहरों पर मिलते हैं, जो पढ़े नहीं जा सके हैं।" },
                { type: "bullet", text: "अभिलेखों में संस्कृत भाषा ईसा की <hl>दूसरी सदी</hl> से मिलने लगती है और <hl>चौथी-पाँचवीं सदी</hl> में इसका व्यापक प्रयोग होने लगा। अभिलेखों में प्रादेशिक भाषा का प्रयोग <hl>नौवीं-दसवीं सदी</hl> में होने लगा।" },
                { type: "bullet", text: "मौर्य, मौर्येत्तर और गुप्तकाल के अधिकांश अभिलेख <hl>कार्पस इनसक्रिप्शओनम इंडिकारम</hl> नामक ग्रंथ माला में संकलित करके प्रकाशित किए गए हैं।" },
                { type: "bullet", text: "<hl>समुद्रगुप्त</hl> की वीणा बजाती हुई मुद्रा वाले सिक्के से उसके संगीत-प्रेमी होने का प्रमाण मिलता है।" },
                { type: "bullet", text: "<hl>अरिकमेडू</hl> (पुदुचेरी के निकट) से रोमन सिक्के प्राप्त हुए हैं।" },
                { type: "bullet", text: "सर्वप्रथम <hl>1863 ई.</hl> में <hl>राबर्ट ब्रूस फुट</hl> ने चेन्नई के पास पल्लवरम् नामक स्थान से भारत का पहला पाषाण कालीन औजार <hl>हस्त-कुठार (Hand-axe)</hl> की खोज की।" },
                { type: "bullet", text: "नोट: राबर्ट ब्रूस-फुट को <hl>भारतीय प्रागैतिहासिक काल का जनक</hl> कहा जाता है।" },
            ],
            en: [
                { type: "heading", text: "History of India" },
                { type: "bullet", text: "This subcontinent, stretching from the Himalayas in the north to the sea in the south, is known as <hl>Bharatvarsha</hl>, called 'the land of the Bharatas' in the epics and Puranas, and its inhabitants were called <hl>Bharati</hl>, meaning descendants of Bharata." },
                { type: "bullet", text: "<hl>Bharata</hl> was the name of an ancient tribe (a group of people living in the north-west), also mentioned in the Rigveda; later the name came to be used for the country." },
                { type: "bullet", text: "Ancient Indians called their country <hl>Jambudvipa</hl>, meaning the island of Jambu (rose-apple) trees." },
                { type: "bullet", text: "Ancient Iranians associated it with the <hl>Sindhu</hl> river, calling it <hl>Hindu</hl> instead of Sindhu. This name later spread across the West and the whole country came to be known by this river's name." },
                { type: "bullet", text: "The Greeks called it '<hl>Inde</hl>' and the Arabs called it <hl>Hind</hl>. In the medieval period the country came to be called <hl>Hindustan</hl>, a word also derived from the Persian word 'Hindu'." },
                { type: "bullet", text: "Based on the Greek word 'Inde', the English came to call it '<hl>India</hl>'." },
                { type: "bullet", text: "The <hl>Vindhya</hl> mountain range divides the country into two parts, north and south. In the north, speakers of <hl>Indo-European</hl> family languages are in the majority, while in the south, speakers of <hl>Dravidian</hl> family languages are in the majority." },
                { type: "bullet", text: "Kings who extended their rule from the Himalayas in the north to Kanyakumari in the south, and from the Brahmaputra valley in the east to across the Indus in the west, were called <hl>Chakravartin</hl>. Such political unity was achieved at least twice. In the third century BCE, <hl>Ashoka</hl> spread his empire across the whole country except the far south; then in the fourth century CE, <hl>Samudragupta's</hl> victorious banner reached from the Ganga valley to the tip of Tamil country." },
                { type: "heading", text: "Note: Composition of India's Population" },
                { type: "bullet", text: "India's population was formed by the mixing of these major races — <hl>Proto-Australoid, Palaeo-Mediterranean, Caucasoid, Negroid, and Mongoloid</hl>." },
                { type: "bullet", text: "For ease of study, Indian history has been divided into three parts — <hl>Ancient India, Medieval India, and Modern India</hl>." },
                { type: "bullet", text: "Note: The credit for first dividing history into three parts goes to the German historian <hl>Christoph Cellarius (1638-1707 CE)</hl>." },
                { type: "heading", text: "Ancient India — 1. Sources of Ancient Indian History" },
                { type: "bullet", text: "Information about ancient Indian history is mainly obtained from <hl>four sources</hl> — 1. Religious texts 2. Historical texts 3. Accounts of foreigners, and 4. Archaeological evidence." },
                { type: "heading", text: "Religious and Historical Texts — Key Information" },
                { type: "bullet", text: "India's oldest religious text is the <hl>Veda</hl>, whose compiler is believed to be the sage <hl>Krishna Dwaipayana Vedavyasa</hl>. The Vedas teach 'Vasudhaiva Kutumbakam'. Indian tradition considers the Vedas eternal and not of human authorship. There are four Vedas — <hl>Rigveda, Samaveda, Yajurveda, and Atharvaveda</hl>. These four Vedas are collectively called <hl>Samhita</hl>." },
                { type: "heading", text: "Rigveda" },
                { type: "bullet", text: "The Rigveda is a systematic collection of hymns (richas). It has <hl>10 mandalas, 1028 suktas</hl> (including 11 suktas of the Valakhilya text), and <hl>10,462 richas</hl>. The sage who recites the hymns of this Veda is called <hl>Hotri</hl>. This Veda provides information about the political system, history, and glory of God among the Aryans." },
                { type: "bullet", text: "The third mandala of the Rigveda, composed by <hl>Vishwamitra</hl>, contains the famous <hl>Gayatri Mantra</hl> dedicated to the sun god Savitri. Its ninth mandala mentions the deity <hl>Soma</hl>." },
                { type: "bullet", text: "The handwritten hymns of its eighth mandala are called <hl>Khila</hl>." },
                { type: "bullet", text: "The <hl>10th mandala</hl> is the largest in the Rigveda. It includes the Nadistuti Sukta (praise of rivers), Purushasukta (Vedic sociology), Nasadiya Sukta (speculations on the creation of the universe), Suryasukta, and marriage hymns." },
                { type: "bullet", text: "The original source of the idea of the four-varna society (described in the 10th mandala of the Rigveda) is the <hl>Purushasukta</hl>, according to which the four varnas (Brahmin, Kshatriya, Vaishya, and Shudra) originated from the mouth, arms, thighs, and feet respectively of the primordial being Brahma." },
                { type: "bullet", text: "Note: The Dharmasutras clearly differentiate the four major classes in terms of their status, occupations, responsibilities, duties, and privileges." },
                { type: "bullet", text: "The word <hl>Aghnya</hl> (that which must not be killed), used in several passages of the Rigveda, refers to the cow." },
                { type: "bullet", text: "The Rigveda mentions <hl>Brahma</hl>, but not the <hl>Atman (soul)</hl>." },
                { type: "heading", text: "BCE and CE" },
                { type: "bullet", text: "The currently used <hl>Gregorian calendar</hl> (Christian calendar/Julian calendar) is based on the (assumed) birth year of Jesus Christ. The time before the birth of Jesus is called <hl>BC (Before Christ)</hl>. Years before Christ are counted in reverse order — for example, Gautama Buddha was born in <hl>563 BCE</hl> and died in <hl>483 BCE</hl>." },
                { type: "bullet", text: "Today, <hl>BCE</hl> is used instead of BC, and <hl>CE (Common Era)</hl> is used instead of AD." },
                { type: "bullet", text: "The era beginning from the birth date of Jesus Christ is called the Christian era, abbreviated as <hl>AD</hl>, from the Latin <hl>Anno Domini</hl>, meaning 'In the year of the Lord (Jesus Christ)'." },
                { type: "bullet", text: "<hl>Vincent Arthur Smith</hl> prepared the first systematic history of ancient India, <hl>'Early History of India'</hl>, in 1904. One-third of the book describes only Alexander's invasion. It describes India as a country of despotic rule that never experienced political unity before the establishment of British rule." },
                { type: "bullet", text: "The <hl>Rigveda</hl> is the oldest source for the legend of Vamana's three strides." },
                { type: "heading", text: "Vamana Avatar" },
                { type: "bullet", text: "The <hl>Vamana Avatar</hl> was the first avatar of Lord Vishnu to appear in human form. His father was <hl>sage Kashyapa</hl> and mother was <hl>Aditi</hl>. He was born as a dwarf Brahmin. According to the Bhagavata Purana, the purpose of the Vamana avatar was for Lord Vishnu to help <hl>Indra</hl> regain control of heaven. Lord Vamana is known as <hl>Upendra</hl> in South India." },
                { type: "bullet", text: "In the Rigveda, <hl>250</hl> hymns are composed for Indra and <hl>200</hl> for Agni." },
                { type: "bullet", text: "As a source for ancient history, in Vedic literature the <hl>Shatapatha Brahmana</hl> ranks next after the Rigveda." },
                { type: "bullet", text: "Note: UNESCO included <hl>30 manuscripts</hl> of the Rigveda, preserved at the Bhandarkar Oriental Research Institute in Pune, in the Memory of the World Register in the year <hl>2007</hl>." },
                { type: "heading", text: "Samaveda" },
                { type: "bullet", text: "The literal meaning of 'Sama' is <hl>song/chant</hl>. This Veda is mainly a collection of hymns (mantras) sung on the occasion of sacrifices. Its reciter is called <hl>Udgatri</hl>. Its compilation is based on the Rigveda. It contains <hl>1810 suktas</hl>, mostly taken from the Rigveda." },
                { type: "bullet", text: "It is called the <hl>father of Indian music</hl>." },
                { type: "heading", text: "Yajurveda" },
                { type: "bullet", text: "The Yajurveda is a compilation of mantras for chanted recitation and rules to be followed at the time of sacrifice. Its reciter is called <hl>Adhvaryu</hl>." },
                { type: "bullet", text: "The Yajurveda contains a compilation of the rules and procedures of sacrifices." },
                { type: "bullet", text: "It also describes the method of sacrifice." },
                { type: "bullet", text: "It is a Veda written in both <hl>prose and verse</hl>." },
                { type: "bullet", text: "Note: Neither the Yajurveda nor the Samaveda contains descriptions of any specific historical event." },
                { type: "heading", text: "Atharvaveda" },
                { type: "bullet", text: "This Veda, composed by <hl>sage Atharva</hl>, has a total of <hl>20 kandas, 36 prapathakas, 731 suktas</hl>, and about <hl>5987 mantras</hl>. It is also known by names such as <hl>Brahmaveda, Atharvangiras Veda, Bhishagveda, and Kshatraveda</hl>." },
                { type: "bullet", text: "The Atharvaveda describes all aspects of dharma, artha, kama, and moksha (<hl>the four Purusharthas</hl>)." },
                { type: "bullet", text: "The <hl>Prithvi Sukta</hl> is considered the representative sukta of the Atharvaveda, found in its <hl>12th kanda</hl>. It contains an expression of national sentiment." },
                { type: "bullet", text: "It describes all aspects of human life — house construction, agricultural improvement, discovery of trade routes, disease cure, marriage and love songs, loyalty to the king, election of the king, plants and medicines, curses, hypnotism, atonement, glory of the motherland, etc. Some mantras also describe sorcery." },
                { type: "bullet", text: "The Atharvaveda describes <hl>Parikshit</hl> as the king of the Kurus and the deity of the realm of death. It gives a good picture of the prosperity of the Kuru country." },
                { type: "bullet", text: "The Atharvaveda calls the people of Magadha <hl>Vratya</hl>, who spoke the Prakrit language." },
                { type: "bullet", text: "The Atharvaveda calls the supreme ruler <hl>Ekarat</hl>." },
                { type: "bullet", text: "The word <hl>Kshetrapali</hl> (mistress of the field) is derived from the Atharvaveda." },
                { type: "bullet", text: "It describes the Sabha and Samiti as the two daughters of Prajapati." },
                { type: "bullet", text: "The Vedas also have several recensions (shakhas) representing different approaches to Vedic study and interpretation. The <hl>Shakala shakha</hl> is the only surviving recension of the Rigveda. The Yajurveda is divided into two branches — <hl>Shukla Yajurveda</hl> and <hl>Krishna Yajurveda</hl>. Madhyandina and Kanva are branches of Shukla Yajurveda (Vajasaneyi Samhita). Kathaka, Kapishthala Maitrayani, and Taittiriya are branches linked to Krishna Yajurveda. Kauthuma, Ranayaniya, and Jaiminiya are branches of the Samaveda. The Atharvaveda had nine branches — Paippalada, Tauda, Mauda, Shaunaka, Jajala, Jalada, Brahmavada, Devadarsha, and Charana Vaidya. Among these, the <hl>Shaunaka Samhita</hl> is fully available, while the Paippalada Samhita is only partially available." },
                { type: "bullet", text: "Note: The oldest Veda is the <hl>Rigveda</hl>, and the most recent is the <hl>Atharvaveda</hl>." },
                { type: "heading", text: "Brahmana, Aranyaka and Upanishad Texts" },
                { type: "bullet", text: "After the Samhitas come the <hl>Brahmanas, Aranyakas, and Upanishads</hl>. These provide information about later Vedic period society and culture." },
                { type: "bullet", text: "The Brahmana texts are written in prose to explain the Vedic Samhitas. The Brahmana text of the Rigveda is the <hl>Aitareya and Kaushitaki</hl>, of the Samaveda the <hl>Panchavimsha</hl>, of the Yajurveda the <hl>Taittiriya and Shatapatha</hl>, and of the Atharvaveda the <hl>Gopatha</hl>." },
                { type: "bullet", text: "These Brahmana texts give us knowledge of events <hl>after Parikshit and before Bimbisara</hl>." },
                { type: "bullet", text: "The <hl>Aitareya</hl> gives the rules of coronation and the names of some ancient kings." },
                { type: "bullet", text: "The <hl>Shatapatha</hl> mentions kings of Gandhara, Shalya, Kaikeya, Kuru, Panchala, Kosala, Videha, etc." },
                { type: "bullet", text: "The Aranyaka provides a philosophical and symbolic expression of the rituals associated with sacrifices." },
                { type: "bullet", text: "There are <hl>108</hl> Upanishads, of which <hl>13</hl> are classified as principal (mukhya) Upanishads. They explain the philosophical ideas connected with sacrifice, the universe, the body, the soul, and Brahman." },
                { type: "bullet", text: "The most degraded status of women is found in the <hl>Maitreyani Samhita</hl>, where woman is described, along with gambling and liquor, as the third major vice of man." },
                { type: "bullet", text: "The Shatapatha Brahmana calls woman the <hl>ardhangini</hl> (better half) of man." },
                { type: "bullet", text: "The <hl>Jabala Upanishad</hl> mentions all four ashramas (stages of life)." },
                { type: "bullet", text: "Among the Smriti texts, the <hl>Manusmriti</hl> is considered the oldest and most authoritative. It is the standard text of the <hl>Shunga period</hl>." },
                { type: "bullet", text: "The <hl>Narada Smriti</hl> provides information about the Gupta era. It is purely a legal text, containing a total of <hl>18 sections and 1028 verses</hl>. It can be called the law-book of ancient India." },
                { type: "heading", text: "Vedangas and Sutras" },
                { type: "bullet", text: "<hl>Six Vedangas</hl> were composed to properly understand the Vedas — Shiksha (phonetics), Kalpa (ritual procedure), Nirukta (etymology), Vyakarana (grammar), Chhanda (metre), and Jyotisha (astronomy)." },
                { type: "bullet", text: "Sutra literature was composed to preserve Vedic literature intact. The <hl>Kalpasutras</hl> are mainly of four types — 1. Shrauta Sutra (sacrificial procedure) 2. Grihyasutra (household duties) 3. Dharmasutra (religious conduct) 4. Shulvasutra (geometry of sacrificial altars)." },
                { type: "bullet", text: "Major sutra authors are: <hl>Gautama, Baudhayana, Apastamba, Vashishtha</hl> (Dharmasutra); <hl>Shankhyayana, Ashvalayana</hl> (Grihyasutra); <hl>Jaimini</hl> (Mimamsa Sutra); <hl>Panini</hl> (grammar sutra, Ashtadhyayi)." },
                { type: "bullet", text: "Among the sutras, the <hl>Gautama Dharmasutra</hl> is considered the oldest." },
                { type: "heading", text: "Puranas" },
                { type: "bullet", text: "The best chronological account of Indian historical legends is found in the Puranas. Their author is believed to be <hl>Lomaharsha or his son Ugrashrava</hl>. There are <hl>18</hl> Puranas, of which only five — <hl>Matsya, Vayu, Vishnu, Brahmanda, and Bhagavata</hl> — contain genealogies of kings." },
                { type: "bullet", text: "The <hl>Vishnu Purana</hl> contains the genealogy of the Maurya dynasty, the <hl>Matsya Purana</hl> that of the Andhra Satavahanas, and the <hl>Vayu Purana</hl> that of the Gupta dynasty." },
                { type: "bullet", text: "Most Puranas are written in simple Sanskrit verse. Women and Shudras, who were not permitted to read the Vedas, could also listen to the Puranas. The Puranas used to be recited by priests in temples." },
                { type: "bullet", text: "Note: Among the Puranas, the <hl>Matsya Purana</hl> is the oldest and most authoritative." },
                { type: "bullet", text: "From a social and cultural viewpoint, the <hl>Agni Purana</hl> is quite important as it describes monarchy as well as agricultural matters." },
                { type: "bullet", text: "The <hl>Kalika Purana</hl> is considered one of the 18 Upapuranas of Hinduism. It is related to the <hl>Shakta sect</hl> of Hinduism." },
                { type: "bullet", text: "Note: The Upanishads were composed before the Puranas." },
                { type: "heading", text: "Buddhist, Jain and Other Literature" },
                { type: "bullet", text: "The <hl>Jataka</hl> tales describe the stories of Buddha's previous births. The main text of Hinayana Buddhism is the <hl>Kathavatthu</hl> (in Pali), composed by the elder <hl>Moggaliputta Tissa</hl> around the third century BCE." },
                { type: "bullet", text: "Jain literature is called <hl>Agama</hl>. The early history of Jainism is known from the '<hl>Kalpasutra</hl>', believed to have been composed by <hl>Bhadrabahu</hl>. It describes the life stories of the Tirthankaras (especially Parshvanath and Mahavira Swami). Jain monks and nuns recite and interpret it during the Paryushana festival. The Jain text <hl>Bhagavati Sutra</hl> gives details of Mahavira's life events." },
                { type: "bullet", text: "Note: Jain texts were composed in the Prakrit language. They were finally compiled in the sixth century CE at <hl>Vallabhi</hl> in Gujarat." },
                { type: "bullet", text: "The author of the <hl>Arthashastra</hl> is <hl>Chanakya (Kautilya or Vishnugupta)</hl>. It contains <hl>15 adhikaranas, 180 prakaranas, and 4000 verses</hl>. It is a legal/administrative text that provides information about Mauryan-era history." },
                { type: "bullet", text: "Note: <hl>Shamashastri</hl> discovered the Arthashastra in 1905 and published its Sanskrit edition for the first time in 1909. Originally, the manuscripts of the Arthashastra were written on palm leaves in Grantha script." },
                { type: "bullet", text: "The first attempt to write historical events chronologically in Sanskrit literature was made by <hl>Kalhana</hl>. Kalhana's book <hl>Rajatarangini</hl> (River of Kings) has <hl>eight cantos (tarangas)</hl>. It describes the rulers of Kashmir from the beginning up to the 12th century." },
                { type: "bullet", text: "The account of the Arab conquest of Sindh, <hl>Chachnama</hl> (or Fathnama), was originally in Arabic, translated into Persian in 1226 by <hl>Ali bin Abu Bakr Kufi</hl>; it was later translated into English and Sindhi in 1900 by <hl>Mirza Kalichbeg</hl>." },
                { type: "bullet", text: "The author of the '<hl>Ashtadhyayi</hl>' (the first book of Sanskrit grammar) is <hl>Panini</hl>, believed to have lived around the 5th century BCE (during the Nanda period)." },
                { type: "bullet", text: "Note: The Ashtadhyayi compiles the rules of Sanskrit grammar through <hl>3996 sutras</hl>. It is the first text to use the word '<hl>Lipi</hl>' (script)." },
                { type: "bullet", text: "Kalhana's <hl>Gargi Samhita</hl> is an astrological text, but it also mentions the Yavana invasion of India." },
                { type: "bullet", text: "<hl>Patanjali</hl> was the priest of Pushyamitra Shunga; his <hl>Mahabhashya</hl> provides information about the history of the Shungas." },
                { type: "bullet", text: "In the Mahabharata, <hl>Bhagadatta</hl>, the ruler of Pragjyotisha (modern Assam), is mentioned as a warrior fighting on the side of the Kauravas." },
                { type: "heading", text: "Information from Foreign Travellers — A. Greek-Roman Writers" },
                { type: "bullet", text: "<hl>Ctesias</hl>: He was the royal physician of Iran. His account of India is unreliable, being full of astonishing tales." },
                { type: "bullet", text: "<hl>Herodotus</hl>: He is called the 'Father of History'. In his book Historica, he described India-Persia relations of the 5th century BCE, but his account is also based on hearsay and rumours." },
                { type: "bullet", text: "Among the writers who accompanied Alexander, the accounts of <hl>Nearchus, Onesicritus, and Aristobulus</hl> are more authentic and reliable." },
                { type: "bullet", text: "<hl>Megasthenes</hl>: He was the ambassador of Seleucus Nicator, who came to the court of Chandragupta Maurya. In his book <hl>Indica</hl>, he wrote about Mauryan-era society and culture." },
                { type: "bullet", text: "<hl>Deimachus</hl>: He was the ambassador of the Syrian king Antiochus, who came to the court of Bindusara." },
                { type: "bullet", text: "<hl>Dionysius</hl>: He was the ambassador of the Egyptian king Ptolemy Philadelphus, who came to the court of Ashoka." },
                { type: "bullet", text: "<hl>Ptolemy</hl>: He wrote a book called 'Geography of India' in the second century." },
                { type: "bullet", text: "<hl>Pliny</hl>: He wrote 'Natural History' in the first century, which gives details of Indian animals, plants, minerals, etc." },
                { type: "bullet", text: "<hl>Periplus of the Erythraean Sea</hl>: The author of this book is unknown. This writer travelled the Indian Ocean around 80 CE and gave information about India's ports and trade goods of that time." },
                { type: "heading", text: "B. Chinese Writers" },
                { type: "bullet", text: "<hl>Fa-Hien</hl>: This Chinese traveller came to the court of Gupta king <hl>Chandragupta II</hl>. He described the society and culture of Madhya Pradesh, and called its people happy and prosperous. He stayed in India for <hl>14 years</hl>." },
                { type: "bullet", text: "<hl>Sung-Yun</hl>: He came to India in <hl>518 CE</hl>. During his three-year journey, he collected accounts of Buddhist attainments." },
                { type: "bullet", text: "<hl>Hiuen Tsang</hl>: He came to India during Harshavardhana's reign. He set out from China for India in <hl>629 CE</hl> and, after about a year's journey, first reached the Indian kingdom of Kapisha. He stayed in India for <hl>15 years</hl> and returned to China in <hl>645 CE</hl>. He came to study at <hl>Nalanda University</hl> in Bihar and to collect Buddhist texts to take back to China. His travel account is famously known as <hl>Si-Yu-Ki</hl>, which describes 138 countries. According to him, the king of Sindh was a Shudra. Hiuen Tsang worshipped images of the Sun and Shiva along with the image of Buddha." },
                { type: "bullet", text: "Note: At the time of Hiuen Tsang's studies, the vice-chancellor of Nalanda University was Acharya <hl>Shilabhadra</hl>. This university was famous for Buddhist philosophy." },
                { type: "bullet", text: "<hl>I-Tsing</hl>: He came to India at the end of the 7th century. He described Nalanda University, Vikramashila University, and India of his time." },
                { type: "heading", text: "C. Arab Writers" },
                { type: "bullet", text: "<hl>Al-Biruni</hl>: He came to India with Mahmud of Ghazni. He was from Khwarezm or Khiva (modern Turkmenistan). His work written in Arabic, '<hl>Kitab-ul-Hind or Tahqiq-e-Hind (Investigation of India)</hl>', remains an important source for historians even today. It sheds good light on Rajput-era society, religion, customs, and politics." },
                { type: "bullet", text: "<hl>Ibn Battuta</hl>: His travelogue written in Arabic, called '<hl>Rehla</hl>', gives very rich information about the social and cultural life of the Indian subcontinent in the 14th century. Impressed by his scholarship upon reaching Delhi in 1333 CE, Sultan <hl>Muhammad bin Tughlaq</hl> appointed him as the Qazi of Delhi." },
                { type: "heading", text: "D. Other Writers" },
                { type: "bullet", text: "<hl>Taranatha</hl>: He was a Tibetan writer. He composed the texts '<hl>Kangyur</hl>' and '<hl>Tengyur</hl>', which provide information about Indian history." },
                { type: "bullet", text: "<hl>Marco Polo</hl>: He came at the end of the 13th century on a journey to the <hl>Pandya</hl> country. His account is useful for studying Pandya history." },
                { type: "heading", text: "Archaeological Evidence" },
                { type: "bullet", text: "The Father of Indian Archaeology is <hl>Sir Alexander Cunningham</hl>." },
                { type: "bullet", text: "<hl>Alexander Rea, A.H. Longhurst, Robert Sewell, James Burgess, and Walter Elliot</hl> were all associated with the excavation of Indian archaeological sites. They excavated sites such as Bhattiprolu, Ghantasala, and Amaravati." },
                { type: "bullet", text: "The <hl>1400 BCE</hl> inscription from '<hl>Bogazkoy</hl>' (Asia Minor) mentions the names of Vedic deities Mitra, Varuna, Indra, and Nasatya (Ashwini Kumaras)." },
                { type: "bullet", text: "Evidence of the development of <hl>Bhagavata (Vaishnava) religion</hl> in central India is found in the Garuda pillar inscription at Besnagar (Vidisha) of <hl>Heliodorus</hl>, ambassador of the Indo-Greek king Antialcidas of Taxila. Heliodorus came to the court of Shunga king Bhagabhadra." },
                { type: "bullet", text: "The word '<hl>Bharatvarsha</hl>' is mentioned for the first time in the <hl>Hathigumpha inscription</hl>." },
                { type: "bullet", text: "The first inscription to give information about famine is the <hl>Sohgaura inscription</hl>, which also mentions preserving grain for use during times of crisis." },
                { type: "bullet", text: "The first information about the <hl>Huna invasion</hl> of India comes from the <hl>Bhitari pillar inscription</hl>." },
                { type: "bullet", text: "The first written evidence of the practice of <hl>Sati</hl> comes from the <hl>Eran inscription</hl> (of ruler Bhanugupta)." },
                { type: "bullet", text: "The entire history of the <hl>Satavahana</hl> kings has been reconstructed on the basis of their inscriptions." },
                { type: "bullet", text: "The <hl>Mandsaur (Dashapura) inscription</hl>, written in Sanskrit by <hl>Vatsabhatti</hl>, mentions the construction of a sun temple by a guild of silk weavers. This inscription is mainly related to Kumaragupta and Bandhuvarman." },
                { type: "bullet", text: "Evidence of pit-dwellings (gartabas) has been found at the Kashmiri Neolithic site of <hl>Burzahom</hl>. These had steps for descent. Here, the practice of burying pet dogs along with humans was prevalent." },
                { type: "bullet", text: "Note: A site (purasthal) refers to a place where remains of objects such as tools, utensils, and buildings are found." },
                { type: "bullet", text: "The oldest coins are called <hl>Aahat (punch-marked) coins</hl>, referred to in literature as <hl>Karshapana</hl>." },
                { type: "bullet", text: "The <hl>Yavana (Indo-Greek) rulers</hl> were the first to write inscriptions on coins." },
                { type: "heading", text: "Important Inscriptions" },
                { type: "bullet", text: "<hl>Hathigumpha Inscription</hl> (undated, Prakrit language) — Ruler: <hl>Kalinga king Kharavela</hl>. This inscription contains the first written mention of the term 'Bharatvarsha'." },
                { type: "bullet", text: "<hl>Junagadh (Girnar) Inscription</hl> (Sanskrit) — Ruler: <hl>Rudradaman I</hl>. He is credited with issuing the first long inscription in Sanskrit. It mentions the restoration of Lake Sudarshan." },
                { type: "bullet", text: "<hl>Nasik Inscription</hl> (Prakrit) — Ruler: <hl>Gautami Balashri</hl>." },
                { type: "bullet", text: "<hl>Prayag Pillar Inscription</hl> (Sanskrit) — Ruler: <hl>Samudragupta</hl>." },
                { type: "bullet", text: "<hl>Aihole Inscription</hl> (Sanskrit) — Ruler: <hl>Pulakeshin II</hl>." },
                { type: "bullet", text: "<hl>Mandsaur (Sondhani) Inscription</hl> (Sanskrit) — Ruler: Malwa king <hl>Yashodharman</hl>." },
                { type: "bullet", text: "<hl>Gwalior Inscription</hl> (Sanskrit) — Ruler: Pratihara king <hl>Bhoja</hl>." },
                { type: "bullet", text: "<hl>Bhitari and Junagadh Inscriptions</hl> (Sanskrit) — Ruler: <hl>Skandagupta</hl>." },
                { type: "bullet", text: "<hl>Deopara Inscription</hl> (Sanskrit) — Ruler: Bengal king <hl>Vijayasena</hl>." },
                { type: "bullet", text: "The study of inscriptions is called <hl>epigraphy</hl>, and the study of the ancient dating of inscriptions and other old documents is called <hl>palaeography</hl>. The largest number of inscriptions are preserved in Mysore. The oldest inscriptions are found on seals of the Harappan civilization, which have not been deciphered." },
                { type: "bullet", text: "Sanskrit begins appearing in inscriptions from the <hl>2nd century CE</hl> onward, and became widely used everywhere by the <hl>4th-5th centuries</hl>. The use of regional/provincial languages in inscriptions began in the <hl>9th-10th centuries</hl>." },
                { type: "bullet", text: "Most inscriptions of the Mauryan, post-Mauryan, and Gupta periods have been compiled and published in the series called <hl>Corpus Inscriptionum Indicarum</hl>." },
                { type: "bullet", text: "The coin of <hl>Samudragupta</hl> depicting him playing the veena provides evidence of his being a lover of music." },
                { type: "bullet", text: "Roman coins have been found at <hl>Arikamedu</hl> (near Puducherry)." },
                { type: "bullet", text: "In <hl>1863 CE</hl>, <hl>Robert Bruce Foote</hl> first discovered India's first Stone Age tool, a <hl>hand-axe</hl>, at Pallavaram near Chennai." },
                { type: "bullet", text: "Note: Robert Bruce Foote is called the <hl>Father of Indian Prehistory</hl>." },
            ]
        },

        "Jainism": {
            hi: [
                { type: "heading", text: "6. जैन धर्म" },
                { type: "bullet", text: "जैनधर्म के संस्थापक एवं प्रथम तीर्थंकर <hl>ऋषभदेव</hl> थे।" },
                { type: "bullet", text: "<hl>कल्पसूत्र</hl> जैन परम्परा का सर्वाधिक लोकप्रिय ग्रंथ है। इसके एक भाग में जैन धर्म के <hl>24 तीर्थंकरों</hl> के जन्म से लेकर निर्वाण तक की विविध घटनाओं का वर्णन किया गया है। उनके जीवन की पाँच प्रमुख घटनाओं को विशेष रूप से प्रस्तुत किया गया है—<hl>गर्भाधान, जन्म, गृहत्याग, ज्ञान प्राप्ति व प्रथम उपदेश</hl>।" },
                { type: "bullet", text: "जैनधर्म के <hl>23वें तीर्थंकर पार्श्वनाथ</hl> थे जो काशी के इक्ष्वाकु वंशीय राजा <hl>अश्वसेन</hl> के पुत्र थे। इन्होंने 30 वर्ष की अवस्था में संन्यास-जीवन को स्वीकारा। इनके द्वारा दी गयी शिक्षा थी—1. हिंसा न करना, 2. सदा सत्य बोलना, 3. चोरी न करना तथा 4. सम्पत्ति न रखना।" },
                { type: "bullet", text: "<hl>महावीर स्वामी</hl> जैन धर्म के <hl>24वें एवं अंतिम तीर्थंकर</hl> हुए।" },
                { type: "bullet", text: "महावीर का जन्म <hl>540 ईसा पूर्व</hl> में <hl>कुण्डग्राम (वैशाली)</hl> में हुआ था। इनके पिता <hl>सिद्धार्थ</hl> 'ज्ञातृक कुल' के सरदार थे और माता <hl>त्रिशला</hl> लिच्छवि राजा <hl>चेटक</hl> की बहन थी।" },
                { type: "bullet", text: "महावीर की पत्नी का नाम <hl>यशोदा</hl> एवं पुत्री का नाम <hl>अनोज्जा प्रियदर्शनी</hl> था।" },
                { type: "bullet", text: "महावीर के बचपन का नाम <hl>वर्द्धमान</hl> था। इन्होंने 30 वर्ष की उम्र में माता-पिता की मृत्यु के पश्चात् अपने बड़े भाई <hl>नंदिवर्धन</hl> से अनुमति लेकर संन्यास-जीवन को स्वीकारा था।" },
                { type: "bullet", text: "<hl>12 वर्षों</hl> की कठिन तपस्या के बाद महावीर को जृम्भिक के समीप <hl>ऋजुपालिका नदी</hl> के तट पर साल वृक्ष के नीचे तपस्या करते हुए सम्पूर्ण ज्ञान (कैवल्य ज्ञान) का बोध हुआ। इसी समय से महावीर <hl>जिन (विजेता), अर्हत (पूज्य)</hl> और <hl>निर्ग्रन्थ (बंधनहीन)</hl> कहलाए।" },
                { type: "heading", text: "महावीर के गर्भाधान का स्वप्न" },
                { type: "bullet", text: "महावीर के गर्भाधान के समय उनकी माता <hl>त्रिशला</hl> ने <hl>14 वस्तुओं</hl> का स्वप्न देखा।" },
                { type: "bullet", text: "14 वस्तुएँ थीं—<hl>हाथी, बैल, शेर, देवी लक्ष्मी, कलश, पालकी, सरोवर, छोटी नदी, अग्नि, ध्वज, माला, रत्नों का ढेर, सूर्य एवं चन्द्रमा</hl>।" },
                { type: "bullet", text: "उन्होंने अपने सपने के बारे में ज्योतिषियों से बात की। ज्योतिषी ने बताया कि वे एक ऐसे पुत्र को जन्म देंगी जो या तो राजाध्यक्ष होगा अथवा एक महान संत।" },
                { type: "heading", text: "महावीर की शिक्षाएँ एवं अनुयायी" },
                { type: "bullet", text: "<hl>उत्तरायण सूत्र</hl> में महावीर की शिक्षाओं का वर्णन है, जहाँ भिक्षुओं के आचार संहिता का पालन करने का वर्णन किया गया है।" },
                { type: "bullet", text: "महावीर ने अपना उपदेश <hl>प्राकृत (अर्धमागधी)</hl> भाषा में दिया।" },
                { type: "bullet", text: "महावीर के अनुयायियों को मूलतः <hl>निर्ग्रंथ</hl> कहा जाता था।" },
                { type: "bullet", text: "महावीर के प्रथम अनुयायी उनके दामाद <hl>जामिल</hl> बने।" },
                { type: "bullet", text: "प्रथम जैन भिक्षुणी नरेश दधिवाहन की पुत्री <hl>चम्पा</hl> थी।" },
                { type: "heading", text: "प्रमुख जैन तीर्थंकर और उनके प्रतीक चिह्न" },
                { type: "bullet", text: "<hl>ऋषभदेव (प्रथम)</hl> — प्रतीक चिह्न: साँड (बैल)" },
                { type: "bullet", text: "<hl>अजितनाथ (द्वितीय)</hl> — प्रतीक चिह्न: हाथी" },
                { type: "bullet", text: "<hl>संभव (तृतीय)</hl> — प्रतीक चिह्न: घोड़ा" },
                { type: "bullet", text: "<hl>संपार्श्व (सप्तम)</hl> — प्रतीक चिह्न: स्वास्तिक" },
                { type: "bullet", text: "<hl>शांति (सोलहवाँ)</hl> — प्रतीक चिह्न: हिरण" },
                { type: "bullet", text: "<hl>अरनाथ (अठारहवाँ)</hl> — प्रतीक चिह्न: मीन (मछली)" },
                { type: "bullet", text: "<hl>नामि (इक्कीसवें)</hl> — प्रतीक चिह्न: नीलकमल" },
                { type: "bullet", text: "<hl>अरिष्टनेमि (बाइसवें)</hl> — प्रतीक चिह्न: शंख" },
                { type: "bullet", text: "<hl>पार्श्व (तेइसवें)</hl> — प्रतीक चिह्न: सर्प" },
                { type: "bullet", text: "<hl>महावीर (चौबीसवें)</hl> — प्रतीक चिह्न: सिंह" },
                { type: "bullet", text: "नोट: दो जैन तीर्थंकरों <hl>ऋषभदेव</hl> एवं <hl>अरिष्टनेमि</hl> के नामों का उल्लेख ऋग्वेद में मिलता है। अरिष्टनेमि को भगवान कृष्ण का निकट संबंधी माना जाता है।" },
                { type: "bullet", text: "महावीर ने अपने शिष्यों को <hl>11 गणधरों</hl> में विभाजित किया।" },
                { type: "bullet", text: "<hl>आर्य सुधर्मा</hl> अकेला ऐसा गणधर था जो महावीर की मृत्यु के बाद भी जीवित रहा और जो जैनधर्म का प्रथम थेरा या मुख्य उपदेशक हुआ।" },
                { type: "bullet", text: "स्वामी महावीर के भिक्षुणी संघ की प्रधान <hl>चन्दना</hl> थी।" },
                { type: "heading", text: "जैन धर्म का विभाजन: श्वेताम्बर एवं दिगम्बर" },
                { type: "bullet", text: "लगभग <hl>300 ईसा पूर्व</hl> में मगध में 12 वर्षों का भीषण अकाल पड़ा, जिसके कारण <hl>भद्रबाहु</hl> अपने शिष्यों सहित कर्नाटक चले गए। किंतु कुछ अनुयायी <hl>स्थूलभद्र</hl> के साथ मगध में ही रुक गए।" },
                { type: "bullet", text: "भद्रबाहु के वापस लौटने पर मगध के साधुओं से उनका गहरा मतभेद हो गया जिसके परिणामस्वरूप जैन मत <hl>श्वेताम्बर</hl> एवं <hl>दिगम्बर</hl> नामक दो सम्प्रदायों में बँट गया।" },
                { type: "bullet", text: "स्थूलभद्र के शिष्य <hl>श्वेताम्बर (श्वेत वस्त्र धारण करने वाले)</hl> एवं भद्रबाहु के शिष्य <hl>दिगम्बर (नग्न रहने वाले)</hl> कहलाए।" },
                { type: "heading", text: "दिगम्बर एवं श्वेताम्बर सम्प्रदायों में अंतर" },
                { type: "bullet", text: "दिगम्बर: ये पाँचों निग्रहों का पालन करते हैं यथा सत्य, अहिंसा, अस्तेय, अपरिग्रह एवं ब्रह्मचर्य।" },
                { type: "bullet", text: "श्वेताम्बर: ये केवल चार निग्रहों का पालन करते हैं यथा सत्य, अहिंसा, अस्तेय एवं अपरिग्रह। ब्रह्मचर्य का पालन नहीं करते।" },
                { type: "bullet", text: "दिगम्बर: यह सम्प्रदाय 6 अनंत पदार्थों का अस्तित्व स्वीकार करता है — आत्मा (जीव), पदार्थ (पुद्गल), अंतरिक्ष (आकाश), गति (धर्म), स्थिरता (अधर्म) तथा समय (काल)।" },
                { type: "bullet", text: "श्वेताम्बर: यह समय (काल) को छोड़कर 5 अनंत पदार्थों का अस्तित्व स्वीकार करता है यथा आत्मा, पदार्थ, अंतरिक्ष, गति एवं स्थिरता।" },
                { type: "bullet", text: "दिगम्बर: इसमें महिलाएँ तीर्थंकर नहीं हो सकतीं।" },
                { type: "bullet", text: "श्वेताम्बर: इसमें महिलाएँ भी तीर्थंकर हो सकती हैं।" },
                { type: "bullet", text: "दिगम्बर: ये मानते हैं कि महावीर ने विवाह नहीं किया था।" },
                { type: "bullet", text: "श्वेताम्बर: ये मानते हैं कि महावीर ने विवाह किया था और उन्हें संतान थी।" },
                { type: "bullet", text: "दिगम्बर: ये मानते हैं कि 19वें तीर्थंकर मल्लिनाथ पुरुष थे।" },
                { type: "bullet", text: "श्वेताम्बर: ये मानते हैं कि मल्लिनाथ स्त्री थीं।" },
                { type: "bullet", text: "दिगम्बर: इनका कहना है कि मूल जैन आगम ग्रंथ खो चुका है।" },
                { type: "bullet", text: "श्वेताम्बर: ये जैन आगम ग्रंथ को स्वीकार करते हैं।" },
                { type: "bullet", text: "दिगम्बर: ये मानते हैं कि कैवल्य प्राप्ति के बाद उपवास करके रहा जा सकता है।" },
                { type: "bullet", text: "श्वेताम्बर: ये मानते हैं कि कैवल्य प्राप्ति के बाद भी भोजन की आवश्यकता पड़ती है।" },
                { type: "bullet", text: "दिगम्बर: ये स्त्रियों के इसी जीवन में मुक्ति का विरोध करते हैं।" },
                { type: "bullet", text: "श्वेताम्बर: ये इसी जीवन में स्त्रियों की मुक्ति की अधिकारिणी मानते हैं।" },
                { type: "bullet", text: "दिगम्बर: ये सफेद वस्त्र नहीं पहनते हैं, क्योंकि इसे निर्वाण (मोक्ष) में बाधक मानते हैं।" },
                { type: "bullet", text: "श्वेताम्बर: ये सफेद वस्त्र पहनते हैं तथा इसे निर्वाण (मोक्ष) में बाधक नहीं मानते हैं।" },
                { type: "heading", text: "जैन संगीतियाँ" },
                { type: "bullet", text: "प्रथम जैन संगीति <hl>300 ईसा पूर्व</hl> में <hl>पाटलिपुत्र</hl> में हुई, जिसकी अध्यक्षता <hl>स्थूलभद्र</hl> ने की।" },
                { type: "bullet", text: "द्वितीय जैन संगीति <hl>512 ई.</hl> में <hl>वल्लभी (गुजरात)</hl> में हुई, जिसकी अध्यक्षता <hl>क्षमाश्रवण</hl> ने की।" },
                { type: "heading", text: "जैन धर्म के सिद्धांत" },
                { type: "bullet", text: "जैनधर्म के त्रिरत्न हैं—1. <hl>सम्यक् दर्शन</hl> (सही विश्वास) 2. <hl>सम्यक ज्ञान</hl> (सही ज्ञान) और 3. <hl>सम्यक आचरण</hl> (सही आचरण)।" },
                { type: "bullet", text: "त्रिरत्न के अनुशीलन में निम्न <hl>पाँच महाव्रतों</hl> का पालन अनिवार्य है—<hl>अहिंसा, सत्य वचन, अस्तेय, अपरिग्रह एवं ब्रह्मचर्य</hl>।" },
                { type: "bullet", text: "जैन धर्म में <hl>चार वर्गों (शिक्षा, अन्न, चिकित्सा और आवास)</hl> के दान के सिद्धान्त ने इसे लोकप्रिय बनाने में मदद की।" },
                { type: "bullet", text: "जैनधर्म में <hl>ईश्वर की मान्यता नहीं</hl> है।" },
                { type: "bullet", text: "जैनधर्म में <hl>आत्मा की मान्यता</hl> है। जैनियों के अनुसार, जीव (आत्मा) न केवल मनुष्यों व पशु-पक्षियों में वरन पेड़-पौधे, पत्थरों व जल में भी पाया जाता है। जैनधर्म के अनुसार एक आत्मा अपने कर्म के आधार पर जन्म एवं मृत्यु के चक्र में भ्रमण करती है।" },
                { type: "heading", text: "जैन दर्शन: जीव-अजीव एवं चार गतियाँ" },
                { type: "bullet", text: "जैन दर्शन में जीवन या अस्तित्व के चार प्रमुख रूप (जिन्हें <hl>गतियाँ</hl> भी कहा जाता है) निम्नलिखित हैं:" },
                { type: "bullet", text: "1. <hl>मनुष्य गति</hl>: मानव का अस्तित्व। जैन मान्यता के अनुसार केवल इसी गति से मोक्ष (जन्म-मरण के चक्र से मुक्ति) प्राप्त किया जा सकता है।" },
                { type: "bullet", text: "2. <hl>देवगति</hl>: स्वर्गीय प्राणियों या देवताओं का अस्तित्व।" },
                { type: "bullet", text: "3. <hl>तिर्यच गति</hl>: पशु, पक्षी, पेड़-पौधे और सूक्ष्म जीवों का अस्तित्व।" },
                { type: "bullet", text: "4. <hl>नरक गति</hl>: नारकीय प्राणियों का अस्तित्व।" },
                { type: "bullet", text: "इन चारों अवस्थाओं से पार जाकर जब आत्मा अपने सभी कर्मों का नाश कर लेती है, तब उसे <hl>मोक्ष</hl> की प्राप्ति होती है।" },
                { type: "bullet", text: "जैन धर्म के अनुसार, सृष्टि का निर्माण <hl>जीव तथा अजीव</hl> नामक दो मूल तत्वों से हुआ है। जीव चेतन तत्व है और अजीव अचेतन जड़ तत्व (<hl>पुद्गल, काल, आकाश, धर्म व अधर्म</hl>) है।" },
                { type: "bullet", text: "महावीर <hl>पुनर्जन्म एवं कर्मवाद</hl> में विश्वास करते थे।" },
                { type: "bullet", text: "जैनधर्म के सप्तभंगी ज्ञान के अन्य नाम <hl>स्यादवाद</hl> व <hl>अनेकांतवाद</hl> हैं, जो जैन धर्म का मौलिक सिद्धांत है।" },
                { type: "bullet", text: "जैनधर्म ने अपने आध्यात्मिक विचारों को <hl>सांख्य दर्शन</hl> से ग्रहण किया। जैन धर्म के प्रमुख त्योहार हैं: <hl>महावीर जयंती, पर्युषण अष्टान्हिका, एवं दीपावली</hl>।" },
                { type: "heading", text: "जैन धर्म से जुड़े राजा एवं प्रमुख स्थल" },
                { type: "bullet", text: "जैनधर्म मानने वाले कुछ राजा थे—<hl>उदयिन, वंदराजा, चन्द्रगुप्त मौर्य, कलिंग नरेश खारवेल, राष्ट्रकूट राजा अमोघवर्ष, चंदेल शासक</hl>।" },
                { type: "bullet", text: "मैसूर के गंग वंश के राजाओं के सेनापति एवं प्रधानमंत्री <hl>चामुण्डाराय</hl> के प्रोत्साहन से कर्नाटक के <hl>श्रवणबेलगोला</hl> में 10वीं शताब्दी के मध्य भाग में विशाल बाहुबलि की ग्रेनाइट पत्थर की मूर्ति (<hl>गोमतेश्वर की मूर्ति</hl>) का निर्माण किया गया।" },
                { type: "bullet", text: "गोमतेश्वर की प्रतिमा <hl>कायोत्सर्ग मुद्रा</hl> में है। इसमें बाहुबलि तपस्या की इस मुद्रा में अपने चारों ओर के वातावरण से अनभिज्ञ दिखाए गए हैं। उनके पैरों में साँप लपेटे हुए तथा चींटियों ने मिट्टी के घरौंदे बना दिए हैं।" },
                { type: "bullet", text: "यह मूर्ति <hl>18 मीटर या 57 फीट</hl> ऊँची है एवं एक ही चट्टान को काटकर बनाई गई है। यह विश्व में एक ही पत्थर से बनी बिना किसी सहारे के खड़ी सबसे लंबी मूर्ति है।" },
                { type: "bullet", text: "राजस्थान में <hl>माउन्ट आबू</hl> पर स्थित जैन मंदिर <hl>विमलशाह</hl> द्वारा बनवाए गए थे।" },
                { type: "bullet", text: "<hl>काठियावाड़ (गुजरात)</hl> में पालिताना के निकट <hl>शत्रुंजय की पहाड़ियों</hl> में एक विशाल जैन तीर्थस्थल है जहाँ एक साथ जुड़े हुए बीसियों मंदिर दर्शनीय हैं।" },
                { type: "bullet", text: "<hl>खजुराहो</hl> में जैन मंदिरों का निर्माण <hl>चंदेल शासकों</hl> द्वारा किया गया।" },
                { type: "bullet", text: "आधुनिक तमिलनाडु के <hl>पुदुकोट्टई</hl> जिले में स्थित <hl>सित्तन्नवासल की गुफाएँ</hl> जैन धर्म से संबंधित हैं।" },
                { type: "bullet", text: "मौर्योत्तर युग में <hl>मथुरा</hl> जैन धर्म का प्रसिद्ध केन्द्र था। मथुरा कला का संबंध जैनधर्म से है।" },
                { type: "heading", text: "महावीर का निर्वाण एवं अन्य तथ्य" },
                { type: "bullet", text: "जैन तीर्थंकरों की जीवनी <hl>भद्रबाहु</hl> द्वारा रचित <hl>कल्पसूत्र</hl> में है।" },
                { type: "bullet", text: "<hl>72 वर्ष</hl> की आयु में महावीर की मृत्यु (निर्वाण) <hl>468 ईसा पूर्व</hl> में बिहार राज्य के <hl>पावापुरी (राजगीर)</hl> में हो गई।" },
                { type: "bullet", text: "मल्लराजा <hl>सृस्तिपाल</hl> के राजप्रासाद में महावीर स्वामी को निर्वाण प्राप्त हुआ था।" },
                { type: "bullet", text: "<hl>जीवक चिन्तामणि</hl> जैन संत <hl>तिरुत्तक्कतेवर</hl> द्वारा लिखित संगम साहित्य का एक जैन महाकाव्य है। यह राजकुमार जीवक के बारे में है और इसे <hl>मन-नूल (विवाह की पुस्तक)</hl> के रूप में जाना जाता है।" },
                { type: "bullet", text: "नोट: छठी से नौवीं शताब्दी के बीच बड़ोदरा के पास <hl>अकोटा (गुजरात)</hl> एवं पश्चिमी भारतीय क्षेत्र में कांस्य की अधिकांश मूर्तियाँ महावीर, पार्श्वनाथ या आदिनाथ जैसे तीर्थंकरों की बनायी जाती थीं। इसमें तीर्थंकरों को एक सिंहासन पर विराजमान दिखाया गया और ये तीर्थंकर अकेले या तीन से 24 तीर्थंकरों के समूह में प्रस्तुत किए गए। इनके अलावा कुछ प्रमुख तीर्थंकरों की शासन देवियों या यक्षिणियों की नारी प्रतिमाएँ भी बनाई जाने लगीं। <hl>चक्रेश्वरी</hl> आदिनाथ की शासन देवी एवं <hl>अंबिका</hl> नेमिनाथ की शासन देवी है।" },
            ],
            en: [
                { type: "heading", text: "6. Jainism" },
                { type: "bullet", text: "The founder and first Tirthankara of Jainism was <hl>Rishabhadeva</hl>." },
                { type: "bullet", text: "The <hl>Kalpasutra</hl> is the most popular text of the Jain tradition. One part of it describes various events in the lives of the <hl>24 Tirthankaras</hl>, from conception to nirvana. Five major events of their lives are specially presented — <hl>conception, birth, renunciation, attainment of knowledge, and first sermon</hl>." },
                { type: "bullet", text: "The <hl>23rd Tirthankara</hl> of Jainism was <hl>Parshvanath</hl>, son of King <hl>Ashvasena</hl> of the Ikshvaku dynasty of Kashi. He accepted the ascetic life at the age of 30. The teachings given by him were — 1. Non-violence, 2. Always speak the truth, 3. Do not steal, and 4. Do not possess property." },
                { type: "bullet", text: "<hl>Mahavira Swami</hl> was the <hl>24th and last Tirthankara</hl> of Jainism." },
                { type: "bullet", text: "Mahavira was born in <hl>540 BCE</hl> at <hl>Kundagrama (Vaishali)</hl>. His father <hl>Siddhartha</hl> was the chief of the 'Jnatrika clan', and his mother <hl>Trishala</hl> was the sister of Lichchhavi king <hl>Chetak</hl>." },
                { type: "bullet", text: "Mahavira's wife was named <hl>Yashoda</hl> and his daughter was named <hl>Anojja Priyadarshini</hl>." },
                { type: "bullet", text: "Mahavira's childhood name was <hl>Vardhamana</hl>. At the age of 30, after the death of his parents, he accepted the ascetic life with the permission of his elder brother <hl>Nandivardhana</hl>." },
                { type: "bullet", text: "After <hl>12 years</hl> of rigorous penance, Mahavira attained complete knowledge (Kaivalya Jnana) while meditating under a Sal tree on the banks of the <hl>Rijupalika river</hl> near Jrimbhika. From this time on, Mahavira came to be called <hl>Jina (Conqueror), Arhat (Worthy of worship)</hl>, and <hl>Nirgrantha (Free of bonds)</hl>." },
                { type: "heading", text: "Mahavira's Conception Dream" },
                { type: "bullet", text: "At the time of Mahavira's conception, his mother <hl>Trishala</hl> saw a dream of <hl>14 objects</hl>." },
                { type: "bullet", text: "The 14 objects were — <hl>elephant, bull, lion, Goddess Lakshmi, pot, palanquin, lake, small river, fire, flag, garland, heap of jewels, sun, and moon</hl>." },
                { type: "bullet", text: "She spoke to astrologers about her dream. The astrologers told her that she would give birth to a son who would either become a great king or a great saint." },
                { type: "heading", text: "Mahavira's Teachings and Followers" },
                { type: "bullet", text: "The <hl>Uttarayana Sutra</hl> describes Mahavira's teachings, where the code of conduct to be followed by monks is described." },
                { type: "bullet", text: "Mahavira gave his teachings in the <hl>Prakrit (Ardhamagadhi)</hl> language." },
                { type: "bullet", text: "Mahavira's followers were originally called <hl>Nirgrantha</hl>." },
                { type: "bullet", text: "Mahavira's first follower was his son-in-law <hl>Jamil</hl>." },
                { type: "bullet", text: "The first Jain nun was <hl>Champa</hl>, daughter of King Dadhivahana." },
                { type: "heading", text: "Major Jain Tirthankaras and their Symbols" },
                { type: "bullet", text: "<hl>Rishabhadeva (1st)</hl> — Symbol: Bull" },
                { type: "bullet", text: "<hl>Ajitnath (2nd)</hl> — Symbol: Elephant" },
                { type: "bullet", text: "<hl>Sambhava (3rd)</hl> — Symbol: Horse" },
                { type: "bullet", text: "<hl>Suparshva (7th)</hl> — Symbol: Swastika" },
                { type: "bullet", text: "<hl>Shanti (16th)</hl> — Symbol: Deer" },
                { type: "bullet", text: "<hl>Arnath (18th)</hl> — Symbol: Fish" },
                { type: "bullet", text: "<hl>Nami (21st)</hl> — Symbol: Blue Lotus" },
                { type: "bullet", text: "<hl>Aristanemi (22nd)</hl> — Symbol: Conch" },
                { type: "bullet", text: "<hl>Parshva (23rd)</hl> — Symbol: Serpent" },
                { type: "bullet", text: "<hl>Mahavira (24th)</hl> — Symbol: Lion" },
                { type: "bullet", text: "Note: The names of two Jain Tirthankaras — <hl>Rishabhadeva</hl> and <hl>Aristanemi</hl> — are found mentioned in the <hl>Rigveda</hl>. Aristanemi is considered a close relative of Lord Krishna." },
                { type: "bullet", text: "Mahavira divided his disciples into <hl>11 Ganadharas</hl>." },
                { type: "bullet", text: "<hl>Arya Sudharma</hl> was the only Ganadhara who survived even after Mahavira's death and became the first Thera (chief preacher) of Jainism." },
                { type: "bullet", text: "The head of Mahavira's order of nuns was <hl>Chandana</hl>." },
                { type: "heading", text: "Division of Jainism: Shwetambara and Digambara" },
                { type: "bullet", text: "Around <hl>300 BCE</hl>, a severe 12-year famine struck Magadha, due to which <hl>Bhadrabahu</hl> moved to Karnataka along with his disciples. However, some followers stayed back in Magadha with <hl>Sthulabhadra</hl>." },
                { type: "bullet", text: "When Bhadrabahu returned, deep differences arose with the monks of Magadha, as a result of which Jainism split into two sects called <hl>Shwetambara</hl> and <hl>Digambara</hl>." },
                { type: "bullet", text: "Sthulabhadra's disciples came to be called <hl>Shwetambara (those who wear white clothes)</hl>, and Bhadrabahu's disciples were called <hl>Digambara (those who remain unclothed)</hl>." },
                { type: "heading", text: "Differences between Digambara and Shwetambara Sects" },
                { type: "bullet", text: "Digambara: They observe all five vows — truth, non-violence, non-stealing, non-possession, and celibacy." },
                { type: "bullet", text: "Shwetambara: They observe only four vows — truth, non-violence, non-stealing, and non-possession. They do not observe celibacy separately." },
                { type: "bullet", text: "Digambara: This sect accepts the existence of 6 eternal substances — soul (jiva), matter (pudgala), space (akasha), motion (dharma), rest (adharma), and time (kala)." },
                { type: "bullet", text: "Shwetambara: This sect accepts only 5 eternal substances, excluding time (kala) — soul, matter, space, motion, and rest." },
                { type: "bullet", text: "Digambara: In this sect, women cannot become Tirthankaras." },
                { type: "bullet", text: "Shwetambara: In this sect, women can also become Tirthankaras." },
                { type: "bullet", text: "Digambara: They believe Mahavira never married." },
                { type: "bullet", text: "Shwetambara: They believe Mahavira married and had a child." },
                { type: "bullet", text: "Digambara: They believe the 19th Tirthankara Mallinath was male." },
                { type: "bullet", text: "Shwetambara: They believe Mallinath was female." },
                { type: "bullet", text: "Digambara: They say the original Jain Agama texts are lost." },
                { type: "bullet", text: "Shwetambara: They accept the Jain Agama texts as authentic." },
                { type: "bullet", text: "Digambara: They believe one can remain fasting even after attaining Kaivalya (omniscience)." },
                { type: "bullet", text: "Shwetambara: They believe food is still needed even after attaining Kaivalya." },
                { type: "bullet", text: "Digambara: They oppose women attaining liberation within the same life/body." },
                { type: "bullet", text: "Shwetambara: They believe women are entitled to liberation in the same life." },
                { type: "bullet", text: "Digambara: They do not wear white clothes, considering it an obstacle to nirvana (moksha)." },
                { type: "bullet", text: "Shwetambara: They wear white clothes and do not consider it an obstacle to nirvana (moksha)." },
                { type: "heading", text: "Jain Councils" },
                { type: "bullet", text: "The first Jain council was held in <hl>300 BCE</hl> at <hl>Pataliputra</hl>, presided over by <hl>Sthulabhadra</hl>." },
                { type: "bullet", text: "The second Jain council was held in <hl>512 CE</hl> at <hl>Vallabhi (Gujarat)</hl>, presided over by <hl>Kshamashravana</hl>." },
                { type: "heading", text: "Principles of Jainism" },
                { type: "bullet", text: "The three jewels (Triratna) of Jainism are — 1. <hl>Samyak Darshan</hl> (Right Faith), 2. <hl>Samyak Jnana</hl> (Right Knowledge), and 3. <hl>Samyak Charitra</hl> (Right Conduct)." },
                { type: "bullet", text: "In practicing the three jewels, observance of the following <hl>five great vows (Panch Mahavrata)</hl> is essential — <hl>non-violence, truthful speech, non-stealing, non-possession, and celibacy</hl>." },
                { type: "bullet", text: "The principle of donating <hl>four essentials (education, food, medicine, and shelter)</hl> in Jainism helped make it popular." },
                { type: "bullet", text: "Jainism does <hl>not believe in the existence of a creator God</hl>." },
                { type: "bullet", text: "Jainism <hl>believes in the existence of the soul (atma)</hl>. According to Jains, the soul (jiva) is found not only in humans and animals but also in plants, stones, and water. According to Jainism, a soul wanders through the cycle of birth and death based on its karma." },
                { type: "heading", text: "Jain Philosophy: Jiva-Ajiva and the Four States of Existence" },
                { type: "bullet", text: "In Jain philosophy, the four main forms of existence (also called <hl>gatis</hl>) are as follows:" },
                { type: "bullet", text: "1. <hl>Manushya Gati (Human state)</hl>: The existence of humans. According to Jain belief, moksha (liberation from the cycle of birth and death) can only be attained from this state." },
                { type: "bullet", text: "2. <hl>Deva Gati (Celestial state)</hl>: The existence of heavenly beings or gods." },
                { type: "bullet", text: "3. <hl>Tiryancha Gati (Animal/plant state)</hl>: The existence of animals, birds, plants, and microorganisms." },
                { type: "bullet", text: "4. <hl>Naraka Gati (Hellish state)</hl>: The existence of hellish beings." },
                { type: "bullet", text: "When the soul goes beyond these four states and destroys all its karmas, it attains <hl>moksha</hl>." },
                { type: "bullet", text: "According to Jainism, creation is formed of two fundamental elements called <hl>Jiva (soul) and Ajiva (non-soul)</hl>. Jiva is the conscious element, and Ajiva is the non-conscious, inert element (<hl>matter, time, space, motion, and rest</hl>)." },
                { type: "bullet", text: "Mahavira believed in <hl>rebirth and the doctrine of karma</hl>." },
                { type: "bullet", text: "Other names for the Jain doctrine of Saptabhangi (sevenfold predication) are <hl>Syadvada</hl> and <hl>Anekantavada</hl>, which are fundamental principles of Jainism." },
                { type: "bullet", text: "Jainism drew its spiritual ideas from <hl>Samkhya philosophy</hl>. The major festivals of Jainism are: <hl>Mahavira Jayanti, Paryushana Ashtanhika, and Deepavali</hl>." },
                { type: "heading", text: "Kings and Major Sites Associated with Jainism" },
                { type: "bullet", text: "Some kings who followed Jainism were — <hl>Udayin, Vandaraja, Chandragupta Maurya, Kalinga king Kharavela, Rashtrakuta king Amoghavarsha, and the Chandela rulers</hl>." },
                { type: "bullet", text: "At the encouragement of <hl>Chamundaraya</hl>, the commander-in-chief and prime minister of the Ganga dynasty kings of Mysore, a massive granite statue of Bahubali (the <hl>Gomateshwara statue</hl>) was built at <hl>Shravanabelagola</hl>, Karnataka, in the mid-10th century." },
                { type: "bullet", text: "The Gomateshwara statue is in the <hl>Kayotsarga posture</hl>. Bahubali is shown in this posture of penance, unaware of his surroundings. Serpents are shown coiled around his feet, and ants have built mud mounds on him." },
                { type: "bullet", text: "This statue is <hl>18 metres (57 feet)</hl> tall and is carved out of a single rock. It is the world's tallest freestanding monolithic statue." },
                { type: "bullet", text: "The Jain temples at <hl>Mount Abu</hl> in Rajasthan were built by <hl>Vimal Shah</hl>." },
                { type: "bullet", text: "There is a vast Jain pilgrimage site in the <hl>Shatrunjaya Hills</hl> near Palitana in <hl>Kathiawar (Gujarat)</hl>, where dozens of interconnected temples can be seen." },
                { type: "bullet", text: "The Jain temples at <hl>Khajuraho</hl> were built by the <hl>Chandela rulers</hl>." },
                { type: "bullet", text: "The <hl>Sittanavasal caves</hl>, located in the <hl>Pudukkottai</hl> district of modern Tamil Nadu, are associated with Jainism." },
                { type: "bullet", text: "In the post-Mauryan era, <hl>Mathura</hl> was a famous centre of Jainism. Mathura art is associated with Jainism." },
                { type: "heading", text: "Mahavira's Nirvana and Other Facts" },
                { type: "bullet", text: "The biography of the Jain Tirthankaras is found in the <hl>Kalpasutra</hl>, composed by <hl>Bhadrabahu</hl>." },
                { type: "bullet", text: "At the age of <hl>72</hl>, Mahavira attained death (nirvana) in <hl>468 BCE</hl> at <hl>Pavapuri (Rajgir)</hl> in Bihar." },
                { type: "bullet", text: "Mahavira Swami attained nirvana in the royal palace of the Malla king <hl>Sristipala</hl>." },
                { type: "bullet", text: "<hl>Jivaka Chintamani</hl> is a Jain epic of Sangam literature written by the Jain saint <hl>Tiruttakkatevar</hl>. It is about Prince Jivaka and is known as the <hl>Man-Nool ('marriage book')</hl>." },
                { type: "bullet", text: "Note: Between the sixth and ninth centuries, most bronze statues near <hl>Akota (Gujarat)</hl>, close to Vadodara, and in the western Indian region, were made of Tirthankaras such as Mahavira, Parshvanath, or Adinath. The Tirthankaras were shown seated on a throne, either alone or in groups of three to twenty-four. Female images of the guardian goddesses (Shasana Devis) or Yakshinis of some major Tirthankaras also began to be made. <hl>Chakreshwari</hl> is the guardian goddess of Adinath, and <hl>Ambika</hl> is the guardian goddess of Neminath." },
            ]
        },

        "Vedic Civilization": {
            hi: [
                { type: "heading", text: "वैदिक सभ्यता" },
                { type: "bullet", text: "ऋग्वेद सबसे प्राचीन वेद है, जिसकी रचना लगभग <hl>1500-1000 ईसा पूर्व</hl> मानी जाती है।" },
                { type: "bullet", text: "वैदिक काल को दो भागों में बाँटा गया है: <hl>ऋग्वैदिक काल</hl> और <hl>उत्तर वैदिक काल</hl>।" },
                { type: "heading", text: "सामाजिक व्यवस्था" },
                { type: "bullet", text: "समाज <hl>वर्ण व्यवस्था</hl> पर आधारित था — ब्राह्मण, क्षत्रिय, वैश्य, शूद्र।" }
            ],
            en: [
                { type: "heading", text: "Vedic Civilization" },
                { type: "bullet", text: "The Rigveda is the oldest Veda, composed around <hl>1500-1000 BCE</hl>." },
                { type: "bullet", text: "The Vedic Age is divided into two parts: the <hl>Early Vedic Period</hl> and the <hl>Later Vedic Period</hl>." },
                { type: "heading", text: "Social Structure" },
                { type: "bullet", text: "Society was based on the <hl>Varna System</hl> — Brahmin, Kshatriya, Vaishya, Shudra." }
            ]
        }
    }
};